// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/apikey"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeyService creates a new instance of MockAPIKeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyService {
	mock := &MockAPIKeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyService is an autogenerated mock type for the APIKeyService type
type MockAPIKeyService struct {
	mock.Mock
}

type MockAPIKeyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyService) EXPECT() *MockAPIKeyService_Expecter {
	return &MockAPIKeyService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) Create(ctx context.Context, userID int, name string) (string, *apikey.APIKey, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 *apikey.APIKey
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (string, *apikey.APIKey, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) string); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) *apikey.APIKey); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apikey.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, string) error); ok {
		r2 = returnFunc(ctx, userID, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIKeyService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeyService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - name string
func (_e *MockAPIKeyService_Expecter) Create(ctx any, userID any, name any) *MockAPIKeyService_Create_Call {
	return &MockAPIKeyService_Create_Call{Call: _e.mock.On("Create", ctx, userID, name)}
}

func (_c *MockAPIKeyService_Create_Call) Run(run func(ctx context.Context, userID int, name string)) *MockAPIKeyService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_Create_Call) Return(s string, aPIKey *apikey.APIKey, err error) *MockAPIKeyService_Create_Call {
	_c.Call.Return(s, aPIKey, err)
	return _c
}

func (_c *MockAPIKeyService_Create_Call) RunAndReturn(run func(ctx context.Context, userID int, name string) (string, *apikey.APIKey, error)) *MockAPIKeyService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) List(ctx context.Context, userID int) ([]*apikey.APIKey, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*apikey.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*apikey.APIKey, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*apikey.APIKey); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*apikey.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAPIKeyService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockAPIKeyService_Expecter) List(ctx any, userID any) *MockAPIKeyService_List_Call {
	return &MockAPIKeyService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockAPIKeyService_List_Call) Run(run func(ctx context.Context, userID int)) *MockAPIKeyService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_List_Call) Return(aPIKeys []*apikey.APIKey, err error) *MockAPIKeyService_List_Call {
	_c.Call.Return(aPIKeys, err)
	return _c
}

func (_c *MockAPIKeyService_List_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*apikey.APIKey, error)) *MockAPIKeyService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockAPIKeyService
func (_mock *MockAPIKeyService) Revoke(ctx context.Context, id int, userID int) (*apikey.APIKey, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 *apikey.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*apikey.APIKey, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *apikey.APIKey); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apikey.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyService_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockAPIKeyService_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID int
func (_e *MockAPIKeyService_Expecter) Revoke(ctx any, id any, userID any) *MockAPIKeyService_Revoke_Call {
	return &MockAPIKeyService_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, userID)}
}

func (_c *MockAPIKeyService_Revoke_Call) Run(run func(ctx context.Context, id int, userID int)) *MockAPIKeyService_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeyService_Revoke_Call) Return(aPIKey *apikey.APIKey, err error) *MockAPIKeyService_Revoke_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyService_Revoke_Call) RunAndReturn(run func(ctx context.Context, id int, userID int) (*apikey.APIKey, error)) *MockAPIKeyService_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
