// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/media"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMediaLister creates a new instance of MockMediaLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaLister {
	mock := &MockMediaLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMediaLister is an autogenerated mock type for the MediaLister type
type MockMediaLister struct {
	mock.Mock
}

type MockMediaLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaLister) EXPECT() *MockMediaLister_Expecter {
	return &MockMediaLister_Expecter{mock: &_m.Mock}
}

// ListByCursor provides a mock function for the type MockMediaLister
func (_mock *MockMediaLister) ListByCursor(ctx context.Context, userID int, limit int, beforeID int) ([]*media.Media, error) {
	ret := _mock.Called(ctx, userID, limit, beforeID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCursor")
	}

	var r0 []*media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*media.Media, error)); ok {
		return returnFunc(ctx, userID, limit, beforeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) []*media.Media); ok {
		r0 = returnFunc(ctx, userID, limit, beforeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, beforeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaLister_ListByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCursor'
type MockMediaLister_ListByCursor_Call struct {
	*mock.Call
}

// ListByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
//   - beforeID int
func (_e *MockMediaLister_Expecter) ListByCursor(ctx any, userID any, limit any, beforeID any) *MockMediaLister_ListByCursor_Call {
	return &MockMediaLister_ListByCursor_Call{Call: _e.mock.On("ListByCursor", ctx, userID, limit, beforeID)}
}

func (_c *MockMediaLister_ListByCursor_Call) Run(run func(ctx context.Context, userID int, limit int, beforeID int)) *MockMediaLister_ListByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMediaLister_ListByCursor_Call) Return(medias []*media.Media, err error) *MockMediaLister_ListByCursor_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockMediaLister_ListByCursor_Call) RunAndReturn(run func(ctx context.Context, userID int, limit int, beforeID int) ([]*media.Media, error)) *MockMediaLister_ListByCursor_Call {
	_c.Call.Return(run)
	return _c
}
