// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/media"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMediaServiceInterface creates a new instance of MockMediaServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaServiceInterface {
	mock := &MockMediaServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMediaServiceInterface is an autogenerated mock type for the MediaServiceInterface type
type MockMediaServiceInterface struct {
	mock.Mock
}

type MockMediaServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaServiceInterface) EXPECT() *MockMediaServiceInterface_Expecter {
	return &MockMediaServiceInterface_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockMediaServiceInterface
func (_mock *MockMediaServiceInterface) Delete(ctx context.Context, id int, userID int, userRole string) error {
	ret := _mock.Called(ctx, id, userID, userRole)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) error); ok {
		r0 = returnFunc(ctx, id, userID, userRole)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaServiceInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMediaServiceInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID int
//   - userRole string
func (_e *MockMediaServiceInterface_Expecter) Delete(ctx any, id any, userID any, userRole any) *MockMediaServiceInterface_Delete_Call {
	return &MockMediaServiceInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID, userRole)}
}

func (_c *MockMediaServiceInterface_Delete_Call) Run(run func(ctx context.Context, id int, userID int, userRole string)) *MockMediaServiceInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMediaServiceInterface_Delete_Call) Return(err error) *MockMediaServiceInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaServiceInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id int, userID int, userRole string) error) *MockMediaServiceInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ForceUpload provides a mock function for the type MockMediaServiceInterface
func (_mock *MockMediaServiceInterface) ForceUpload(ctx context.Context, req media.UploadRequest) (*media.Media, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ForceUpload")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, media.UploadRequest) (*media.Media, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, media.UploadRequest) *media.Media); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, media.UploadRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaServiceInterface_ForceUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForceUpload'
type MockMediaServiceInterface_ForceUpload_Call struct {
	*mock.Call
}

// ForceUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - req media.UploadRequest
func (_e *MockMediaServiceInterface_Expecter) ForceUpload(ctx any, req any) *MockMediaServiceInterface_ForceUpload_Call {
	return &MockMediaServiceInterface_ForceUpload_Call{Call: _e.mock.On("ForceUpload", ctx, req)}
}

func (_c *MockMediaServiceInterface_ForceUpload_Call) Run(run func(ctx context.Context, req media.UploadRequest)) *MockMediaServiceInterface_ForceUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 media.UploadRequest
		if args[1] != nil {
			arg1 = args[1].(media.UploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaServiceInterface_ForceUpload_Call) Return(media1 *media.Media, err error) *MockMediaServiceInterface_ForceUpload_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *MockMediaServiceInterface_ForceUpload_Call) RunAndReturn(run func(ctx context.Context, req media.UploadRequest) (*media.Media, error)) *MockMediaServiceInterface_ForceUpload_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateFromBytes provides a mock function for the type MockMediaServiceInterface
func (_mock *MockMediaServiceInterface) GenerateFromBytes(ctx context.Context, imageBytes []byte, userID int, altText string, originalFilename string) (*media.Media, error) {
	ret := _mock.Called(ctx, imageBytes, userID, altText, originalFilename)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromBytes")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, string, string) (*media.Media, error)); ok {
		return returnFunc(ctx, imageBytes, userID, altText, originalFilename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, string, string) *media.Media); ok {
		r0 = returnFunc(ctx, imageBytes, userID, altText, originalFilename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, int, string, string) error); ok {
		r1 = returnFunc(ctx, imageBytes, userID, altText, originalFilename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaServiceInterface_GenerateFromBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFromBytes'
type MockMediaServiceInterface_GenerateFromBytes_Call struct {
	*mock.Call
}

// GenerateFromBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - imageBytes []byte
//   - userID int
//   - altText string
//   - originalFilename string
func (_e *MockMediaServiceInterface_Expecter) GenerateFromBytes(ctx any, imageBytes any, userID any, altText any, originalFilename any) *MockMediaServiceInterface_GenerateFromBytes_Call {
	return &MockMediaServiceInterface_GenerateFromBytes_Call{Call: _e.mock.On("GenerateFromBytes", ctx, imageBytes, userID, altText, originalFilename)}
}

func (_c *MockMediaServiceInterface_GenerateFromBytes_Call) Run(run func(ctx context.Context, imageBytes []byte, userID int, altText string, originalFilename string)) *MockMediaServiceInterface_GenerateFromBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMediaServiceInterface_GenerateFromBytes_Call) Return(media1 *media.Media, err error) *MockMediaServiceInterface_GenerateFromBytes_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *MockMediaServiceInterface_GenerateFromBytes_Call) RunAndReturn(run func(ctx context.Context, imageBytes []byte, userID int, altText string, originalFilename string) (*media.Media, error)) *MockMediaServiceInterface_GenerateFromBytes_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockMediaServiceInterface
func (_mock *MockMediaServiceInterface) GetAll(ctx context.Context, limit int, offset int) ([]*media.Media, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*media.Media, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*media.Media); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaServiceInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockMediaServiceInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockMediaServiceInterface_Expecter) GetAll(ctx any, limit any, offset any) *MockMediaServiceInterface_GetAll_Call {
	return &MockMediaServiceInterface_GetAll_Call{Call: _e.mock.On("GetAll", ctx, limit, offset)}
}

func (_c *MockMediaServiceInterface_GetAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockMediaServiceInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMediaServiceInterface_GetAll_Call) Return(medias []*media.Media, err error) *MockMediaServiceInterface_GetAll_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockMediaServiceInterface_GetAll_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*media.Media, error)) *MockMediaServiceInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockMediaServiceInterface
func (_mock *MockMediaServiceInterface) GetByID(ctx context.Context, id int) (*media.Media, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*media.Media, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *media.Media); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaServiceInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMediaServiceInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockMediaServiceInterface_Expecter) GetByID(ctx any, id any) *MockMediaServiceInterface_GetByID_Call {
	return &MockMediaServiceInterface_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockMediaServiceInterface_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockMediaServiceInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaServiceInterface_GetByID_Call) Return(media1 *media.Media, err error) *MockMediaServiceInterface_GetByID_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *MockMediaServiceInterface_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*media.Media, error)) *MockMediaServiceInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMedia provides a mock function for the type MockMediaServiceInterface
func (_mock *MockMediaServiceInterface) SearchMedia(ctx context.Context, search string, dateFilter string, limit int, offset int) ([]*media.Media, error) {
	ret := _mock.Called(ctx, search, dateFilter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchMedia")
	}

	var r0 []*media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*media.Media, error)); ok {
		return returnFunc(ctx, search, dateFilter, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*media.Media); ok {
		r0 = returnFunc(ctx, search, dateFilter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, search, dateFilter, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaServiceInterface_SearchMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMedia'
type MockMediaServiceInterface_SearchMedia_Call struct {
	*mock.Call
}

// SearchMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - dateFilter string
//   - limit int
//   - offset int
func (_e *MockMediaServiceInterface_Expecter) SearchMedia(ctx any, search any, dateFilter any, limit any, offset any) *MockMediaServiceInterface_SearchMedia_Call {
	return &MockMediaServiceInterface_SearchMedia_Call{Call: _e.mock.On("SearchMedia", ctx, search, dateFilter, limit, offset)}
}

func (_c *MockMediaServiceInterface_SearchMedia_Call) Run(run func(ctx context.Context, search string, dateFilter string, limit int, offset int)) *MockMediaServiceInterface_SearchMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMediaServiceInterface_SearchMedia_Call) Return(medias []*media.Media, err error) *MockMediaServiceInterface_SearchMedia_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockMediaServiceInterface_SearchMedia_Call) RunAndReturn(run func(ctx context.Context, search string, dateFilter string, limit int, offset int) ([]*media.Media, error)) *MockMediaServiceInterface_SearchMedia_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockMediaServiceInterface
func (_mock *MockMediaServiceInterface) Upload(ctx context.Context, req media.UploadRequest) (*media.Media, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, media.UploadRequest) (*media.Media, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, media.UploadRequest) *media.Media); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, media.UploadRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaServiceInterface_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockMediaServiceInterface_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - req media.UploadRequest
func (_e *MockMediaServiceInterface_Expecter) Upload(ctx any, req any) *MockMediaServiceInterface_Upload_Call {
	return &MockMediaServiceInterface_Upload_Call{Call: _e.mock.On("Upload", ctx, req)}
}

func (_c *MockMediaServiceInterface_Upload_Call) Run(run func(ctx context.Context, req media.UploadRequest)) *MockMediaServiceInterface_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 media.UploadRequest
		if args[1] != nil {
			arg1 = args[1].(media.UploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaServiceInterface_Upload_Call) Return(media1 *media.Media, err error) *MockMediaServiceInterface_Upload_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *MockMediaServiceInterface_Upload_Call) RunAndReturn(run func(ctx context.Context, req media.UploadRequest) (*media.Media, error)) *MockMediaServiceInterface_Upload_Call {
	_c.Call.Return(run)
	return _c
}
