// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/aristorinjuang/lesstruct/internal/domain/posttype"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostTypeLister creates a new instance of MockPostTypeLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostTypeLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostTypeLister {
	mock := &MockPostTypeLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostTypeLister is an autogenerated mock type for the PostTypeLister type
type MockPostTypeLister struct {
	mock.Mock
}

type MockPostTypeLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostTypeLister) EXPECT() *MockPostTypeLister_Expecter {
	return &MockPostTypeLister_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockPostTypeLister
func (_mock *MockPostTypeLister) GetAll() []posttype.PostType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []posttype.PostType
	if returnFunc, ok := ret.Get(0).(func() []posttype.PostType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]posttype.PostType)
		}
	}
	return r0
}

// MockPostTypeLister_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockPostTypeLister_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockPostTypeLister_Expecter) GetAll() *MockPostTypeLister_GetAll_Call {
	return &MockPostTypeLister_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockPostTypeLister_GetAll_Call) Run(run func()) *MockPostTypeLister_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostTypeLister_GetAll_Call) Return(postTypes []posttype.PostType) *MockPostTypeLister_GetAll_Call {
	_c.Call.Return(postTypes)
	return _c
}

func (_c *MockPostTypeLister_GetAll_Call) RunAndReturn(run func() []posttype.PostType) *MockPostTypeLister_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
