// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTextGenerationService creates a new instance of MockTextGenerationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTextGenerationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTextGenerationService {
	mock := &MockTextGenerationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTextGenerationService is an autogenerated mock type for the TextGenerationService type
type MockTextGenerationService struct {
	mock.Mock
}

type MockTextGenerationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTextGenerationService) EXPECT() *MockTextGenerationService_Expecter {
	return &MockTextGenerationService_Expecter{mock: &_m.Mock}
}

// EnhanceText provides a mock function for the type MockTextGenerationService
func (_mock *MockTextGenerationService) EnhanceText(ctx context.Context, content string) (string, error) {
	ret := _mock.Called(ctx, content)

	if len(ret) == 0 {
		panic("no return value specified for EnhanceText")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, content)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, content)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTextGenerationService_EnhanceText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnhanceText'
type MockTextGenerationService_EnhanceText_Call struct {
	*mock.Call
}

// EnhanceText is a helper method to define mock.On call
//   - ctx context.Context
//   - content string
func (_e *MockTextGenerationService_Expecter) EnhanceText(ctx any, content any) *MockTextGenerationService_EnhanceText_Call {
	return &MockTextGenerationService_EnhanceText_Call{Call: _e.mock.On("EnhanceText", ctx, content)}
}

func (_c *MockTextGenerationService_EnhanceText_Call) Run(run func(ctx context.Context, content string)) *MockTextGenerationService_EnhanceText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTextGenerationService_EnhanceText_Call) Return(s string, err error) *MockTextGenerationService_EnhanceText_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTextGenerationService_EnhanceText_Call) RunAndReturn(run func(ctx context.Context, content string) (string, error)) *MockTextGenerationService_EnhanceText_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateText provides a mock function for the type MockTextGenerationService
func (_mock *MockTextGenerationService) TranslateText(ctx context.Context, content string, sourceLang string, targetLang string) (string, error) {
	ret := _mock.Called(ctx, content, sourceLang, targetLang)

	if len(ret) == 0 {
		panic("no return value specified for TranslateText")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, content, sourceLang, targetLang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, content, sourceLang, targetLang)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, content, sourceLang, targetLang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTextGenerationService_TranslateText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateText'
type MockTextGenerationService_TranslateText_Call struct {
	*mock.Call
}

// TranslateText is a helper method to define mock.On call
//   - ctx context.Context
//   - content string
//   - sourceLang string
//   - targetLang string
func (_e *MockTextGenerationService_Expecter) TranslateText(ctx any, content any, sourceLang any, targetLang any) *MockTextGenerationService_TranslateText_Call {
	return &MockTextGenerationService_TranslateText_Call{Call: _e.mock.On("TranslateText", ctx, content, sourceLang, targetLang)}
}

func (_c *MockTextGenerationService_TranslateText_Call) Run(run func(ctx context.Context, content string, sourceLang string, targetLang string)) *MockTextGenerationService_TranslateText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTextGenerationService_TranslateText_Call) Return(s string, err error) *MockTextGenerationService_TranslateText_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTextGenerationService_TranslateText_Call) RunAndReturn(run func(ctx context.Context, content string, sourceLang string, targetLang string) (string, error)) *MockTextGenerationService_TranslateText_Call {
	_c.Call.Return(run)
	return _c
}
