// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/content"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSlugResolver creates a new instance of MockSlugResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlugResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlugResolver {
	mock := &MockSlugResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlugResolver is an autogenerated mock type for the SlugResolver type
type MockSlugResolver struct {
	mock.Mock
}

type MockSlugResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlugResolver) EXPECT() *MockSlugResolver_Expecter {
	return &MockSlugResolver_Expecter{mock: &_m.Mock}
}

// GetBySlugAndLanguage provides a mock function for the type MockSlugResolver
func (_mock *MockSlugResolver) GetBySlugAndLanguage(ctx context.Context, slug string, language string) (*content.Content, error) {
	ret := _mock.Called(ctx, slug, language)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlugAndLanguage")
	}

	var r0 *content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*content.Content, error)); ok {
		return returnFunc(ctx, slug, language)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *content.Content); ok {
		r0 = returnFunc(ctx, slug, language)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, slug, language)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlugResolver_GetBySlugAndLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlugAndLanguage'
type MockSlugResolver_GetBySlugAndLanguage_Call struct {
	*mock.Call
}

// GetBySlugAndLanguage is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - language string
func (_e *MockSlugResolver_Expecter) GetBySlugAndLanguage(ctx any, slug any, language any) *MockSlugResolver_GetBySlugAndLanguage_Call {
	return &MockSlugResolver_GetBySlugAndLanguage_Call{Call: _e.mock.On("GetBySlugAndLanguage", ctx, slug, language)}
}

func (_c *MockSlugResolver_GetBySlugAndLanguage_Call) Run(run func(ctx context.Context, slug string, language string)) *MockSlugResolver_GetBySlugAndLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSlugResolver_GetBySlugAndLanguage_Call) Return(content1 *content.Content, err error) *MockSlugResolver_GetBySlugAndLanguage_Call {
	_c.Call.Return(content1, err)
	return _c
}

func (_c *MockSlugResolver_GetBySlugAndLanguage_Call) RunAndReturn(run func(ctx context.Context, slug string, language string) (*content.Content, error)) *MockSlugResolver_GetBySlugAndLanguage_Call {
	_c.Call.Return(run)
	return _c
}

// SlugExists provides a mock function for the type MockSlugResolver
func (_mock *MockSlugResolver) SlugExists(ctx context.Context, slug string, language string) (bool, error) {
	ret := _mock.Called(ctx, slug, language)

	if len(ret) == 0 {
		panic("no return value specified for SlugExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, slug, language)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, slug, language)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, slug, language)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlugResolver_SlugExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlugExists'
type MockSlugResolver_SlugExists_Call struct {
	*mock.Call
}

// SlugExists is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - language string
func (_e *MockSlugResolver_Expecter) SlugExists(ctx any, slug any, language any) *MockSlugResolver_SlugExists_Call {
	return &MockSlugResolver_SlugExists_Call{Call: _e.mock.On("SlugExists", ctx, slug, language)}
}

func (_c *MockSlugResolver_SlugExists_Call) Run(run func(ctx context.Context, slug string, language string)) *MockSlugResolver_SlugExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSlugResolver_SlugExists_Call) Return(b bool, err error) *MockSlugResolver_SlugExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSlugResolver_SlugExists_Call) RunAndReturn(run func(ctx context.Context, slug string, language string) (bool, error)) *MockSlugResolver_SlugExists_Call {
	_c.Call.Return(run)
	return _c
}
