// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBlockedEmailRepo creates a new instance of MockBlockedEmailRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockedEmailRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockedEmailRepo {
	mock := &MockBlockedEmailRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockedEmailRepo is an autogenerated mock type for the BlockedEmailRepo type
type MockBlockedEmailRepo struct {
	mock.Mock
}

type MockBlockedEmailRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockedEmailRepo) EXPECT() *MockBlockedEmailRepo_Expecter {
	return &MockBlockedEmailRepo_Expecter{mock: &_m.Mock}
}

// BlockEmail provides a mock function for the type MockBlockedEmailRepo
func (_mock *MockBlockedEmailRepo) BlockEmail(ctx context.Context, email string, reason string) error {
	ret := _mock.Called(ctx, email, reason)

	if len(ret) == 0 {
		panic("no return value specified for BlockEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockedEmailRepo_BlockEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockEmail'
type MockBlockedEmailRepo_BlockEmail_Call struct {
	*mock.Call
}

// BlockEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - reason string
func (_e *MockBlockedEmailRepo_Expecter) BlockEmail(ctx any, email any, reason any) *MockBlockedEmailRepo_BlockEmail_Call {
	return &MockBlockedEmailRepo_BlockEmail_Call{Call: _e.mock.On("BlockEmail", ctx, email, reason)}
}

func (_c *MockBlockedEmailRepo_BlockEmail_Call) Run(run func(ctx context.Context, email string, reason string)) *MockBlockedEmailRepo_BlockEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlockedEmailRepo_BlockEmail_Call) Return(err error) *MockBlockedEmailRepo_BlockEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockedEmailRepo_BlockEmail_Call) RunAndReturn(run func(ctx context.Context, email string, reason string) error) *MockBlockedEmailRepo_BlockEmail_Call {
	_c.Call.Return(run)
	return _c
}

// IsEmailBlocked provides a mock function for the type MockBlockedEmailRepo
func (_mock *MockBlockedEmailRepo) IsEmailBlocked(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for IsEmailBlocked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockedEmailRepo_IsEmailBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmailBlocked'
type MockBlockedEmailRepo_IsEmailBlocked_Call struct {
	*mock.Call
}

// IsEmailBlocked is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockBlockedEmailRepo_Expecter) IsEmailBlocked(ctx any, email any) *MockBlockedEmailRepo_IsEmailBlocked_Call {
	return &MockBlockedEmailRepo_IsEmailBlocked_Call{Call: _e.mock.On("IsEmailBlocked", ctx, email)}
}

func (_c *MockBlockedEmailRepo_IsEmailBlocked_Call) Run(run func(ctx context.Context, email string)) *MockBlockedEmailRepo_IsEmailBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockedEmailRepo_IsEmailBlocked_Call) Return(b bool, err error) *MockBlockedEmailRepo_IsEmailBlocked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlockedEmailRepo_IsEmailBlocked_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockBlockedEmailRepo_IsEmailBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// UnblockEmail provides a mock function for the type MockBlockedEmailRepo
func (_mock *MockBlockedEmailRepo) UnblockEmail(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UnblockEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockedEmailRepo_UnblockEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnblockEmail'
type MockBlockedEmailRepo_UnblockEmail_Call struct {
	*mock.Call
}

// UnblockEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockBlockedEmailRepo_Expecter) UnblockEmail(ctx any, email any) *MockBlockedEmailRepo_UnblockEmail_Call {
	return &MockBlockedEmailRepo_UnblockEmail_Call{Call: _e.mock.On("UnblockEmail", ctx, email)}
}

func (_c *MockBlockedEmailRepo_UnblockEmail_Call) Run(run func(ctx context.Context, email string)) *MockBlockedEmailRepo_UnblockEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockedEmailRepo_UnblockEmail_Call) Return(err error) *MockBlockedEmailRepo_UnblockEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockedEmailRepo_UnblockEmail_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockBlockedEmailRepo_UnblockEmail_Call {
	_c.Call.Return(run)
	return _c
}
