// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailUpdateTokenRepo creates a new instance of MockEmailUpdateTokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailUpdateTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailUpdateTokenRepo {
	mock := &MockEmailUpdateTokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailUpdateTokenRepo is an autogenerated mock type for the EmailUpdateTokenRepo type
type MockEmailUpdateTokenRepo struct {
	mock.Mock
}

type MockEmailUpdateTokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailUpdateTokenRepo) EXPECT() *MockEmailUpdateTokenRepo_Expecter {
	return &MockEmailUpdateTokenRepo_Expecter{mock: &_m.Mock}
}

// CleanUpExpiredTokens provides a mock function for the type MockEmailUpdateTokenRepo
func (_mock *MockEmailUpdateTokenRepo) CleanUpExpiredTokens(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanUpExpiredTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanUpExpiredTokens'
type MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call struct {
	*mock.Call
}

// CleanUpExpiredTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEmailUpdateTokenRepo_Expecter) CleanUpExpiredTokens(ctx any) *MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call {
	return &MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call{Call: _e.mock.On("CleanUpExpiredTokens", ctx)}
}

func (_c *MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call) Run(run func(ctx context.Context)) *MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call) Return(err error) *MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call) RunAndReturn(run func(ctx context.Context) error) *MockEmailUpdateTokenRepo_CleanUpExpiredTokens_Call {
	_c.Call.Return(run)
	return _c
}

// CreateToken provides a mock function for the type MockEmailUpdateTokenRepo
func (_mock *MockEmailUpdateTokenRepo) CreateToken(ctx context.Context, token string, userID int, newEmail string) error {
	ret := _mock.Called(ctx, token, userID, newEmail)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) error); ok {
		r0 = returnFunc(ctx, token, userID, newEmail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailUpdateTokenRepo_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockEmailUpdateTokenRepo_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID int
//   - newEmail string
func (_e *MockEmailUpdateTokenRepo_Expecter) CreateToken(ctx any, token any, userID any, newEmail any) *MockEmailUpdateTokenRepo_CreateToken_Call {
	return &MockEmailUpdateTokenRepo_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, token, userID, newEmail)}
}

func (_c *MockEmailUpdateTokenRepo_CreateToken_Call) Run(run func(ctx context.Context, token string, userID int, newEmail string)) *MockEmailUpdateTokenRepo_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailUpdateTokenRepo_CreateToken_Call) Return(err error) *MockEmailUpdateTokenRepo_CreateToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailUpdateTokenRepo_CreateToken_Call) RunAndReturn(run func(ctx context.Context, token string, userID int, newEmail string) error) *MockEmailUpdateTokenRepo_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteToken provides a mock function for the type MockEmailUpdateTokenRepo
func (_mock *MockEmailUpdateTokenRepo) DeleteToken(ctx context.Context, tokenID int) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailUpdateTokenRepo_DeleteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteToken'
type MockEmailUpdateTokenRepo_DeleteToken_Call struct {
	*mock.Call
}

// DeleteToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID int
func (_e *MockEmailUpdateTokenRepo_Expecter) DeleteToken(ctx any, tokenID any) *MockEmailUpdateTokenRepo_DeleteToken_Call {
	return &MockEmailUpdateTokenRepo_DeleteToken_Call{Call: _e.mock.On("DeleteToken", ctx, tokenID)}
}

func (_c *MockEmailUpdateTokenRepo_DeleteToken_Call) Run(run func(ctx context.Context, tokenID int)) *MockEmailUpdateTokenRepo_DeleteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailUpdateTokenRepo_DeleteToken_Call) Return(err error) *MockEmailUpdateTokenRepo_DeleteToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailUpdateTokenRepo_DeleteToken_Call) RunAndReturn(run func(ctx context.Context, tokenID int) error) *MockEmailUpdateTokenRepo_DeleteToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function for the type MockEmailUpdateTokenRepo
func (_mock *MockEmailUpdateTokenRepo) GetToken(ctx context.Context, token string) (*repository.EmailUpdateToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 *repository.EmailUpdateToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.EmailUpdateToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.EmailUpdateToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.EmailUpdateToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailUpdateTokenRepo_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockEmailUpdateTokenRepo_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockEmailUpdateTokenRepo_Expecter) GetToken(ctx any, token any) *MockEmailUpdateTokenRepo_GetToken_Call {
	return &MockEmailUpdateTokenRepo_GetToken_Call{Call: _e.mock.On("GetToken", ctx, token)}
}

func (_c *MockEmailUpdateTokenRepo_GetToken_Call) Run(run func(ctx context.Context, token string)) *MockEmailUpdateTokenRepo_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailUpdateTokenRepo_GetToken_Call) Return(emailUpdateToken *repository.EmailUpdateToken, err error) *MockEmailUpdateTokenRepo_GetToken_Call {
	_c.Call.Return(emailUpdateToken, err)
	return _c
}

func (_c *MockEmailUpdateTokenRepo_GetToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*repository.EmailUpdateToken, error)) *MockEmailUpdateTokenRepo_GetToken_Call {
	_c.Call.Return(run)
	return _c
}
