// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/aristorinjuang/lesstruct/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFailedLoginAttemptRepo creates a new instance of MockFailedLoginAttemptRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFailedLoginAttemptRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFailedLoginAttemptRepo {
	mock := &MockFailedLoginAttemptRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFailedLoginAttemptRepo is an autogenerated mock type for the FailedLoginAttemptRepo type
type MockFailedLoginAttemptRepo struct {
	mock.Mock
}

type MockFailedLoginAttemptRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFailedLoginAttemptRepo) EXPECT() *MockFailedLoginAttemptRepo_Expecter {
	return &MockFailedLoginAttemptRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFailedLoginAttemptRepo
func (_mock *MockFailedLoginAttemptRepo) Create(ctx context.Context, attempt *repository.FailedLoginAttempt) error {
	ret := _mock.Called(ctx, attempt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.FailedLoginAttempt) error); ok {
		r0 = returnFunc(ctx, attempt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFailedLoginAttemptRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFailedLoginAttemptRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - attempt *repository.FailedLoginAttempt
func (_e *MockFailedLoginAttemptRepo_Expecter) Create(ctx any, attempt any) *MockFailedLoginAttemptRepo_Create_Call {
	return &MockFailedLoginAttemptRepo_Create_Call{Call: _e.mock.On("Create", ctx, attempt)}
}

func (_c *MockFailedLoginAttemptRepo_Create_Call) Run(run func(ctx context.Context, attempt *repository.FailedLoginAttempt)) *MockFailedLoginAttemptRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.FailedLoginAttempt
		if args[1] != nil {
			arg1 = args[1].(*repository.FailedLoginAttempt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFailedLoginAttemptRepo_Create_Call) Return(err error) *MockFailedLoginAttemptRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFailedLoginAttemptRepo_Create_Call) RunAndReturn(run func(ctx context.Context, attempt *repository.FailedLoginAttempt) error) *MockFailedLoginAttemptRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFailedLoginAttemptRepo
func (_mock *MockFailedLoginAttemptRepo) Delete(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFailedLoginAttemptRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFailedLoginAttemptRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockFailedLoginAttemptRepo_Expecter) Delete(ctx any, userID any) *MockFailedLoginAttemptRepo_Delete_Call {
	return &MockFailedLoginAttemptRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, userID)}
}

func (_c *MockFailedLoginAttemptRepo_Delete_Call) Run(run func(ctx context.Context, userID int)) *MockFailedLoginAttemptRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFailedLoginAttemptRepo_Delete_Call) Return(err error) *MockFailedLoginAttemptRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFailedLoginAttemptRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockFailedLoginAttemptRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockFailedLoginAttemptRepo
func (_mock *MockFailedLoginAttemptRepo) GetByUserID(ctx context.Context, userID int) (*repository.FailedLoginAttempt, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *repository.FailedLoginAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*repository.FailedLoginAttempt, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *repository.FailedLoginAttempt); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FailedLoginAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFailedLoginAttemptRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockFailedLoginAttemptRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockFailedLoginAttemptRepo_Expecter) GetByUserID(ctx any, userID any) *MockFailedLoginAttemptRepo_GetByUserID_Call {
	return &MockFailedLoginAttemptRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockFailedLoginAttemptRepo_GetByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockFailedLoginAttemptRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFailedLoginAttemptRepo_GetByUserID_Call) Return(failedLoginAttempt *repository.FailedLoginAttempt, err error) *MockFailedLoginAttemptRepo_GetByUserID_Call {
	_c.Call.Return(failedLoginAttempt, err)
	return _c
}

func (_c *MockFailedLoginAttemptRepo_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) (*repository.FailedLoginAttempt, error)) *MockFailedLoginAttemptRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementAttempts provides a mock function for the type MockFailedLoginAttemptRepo
func (_mock *MockFailedLoginAttemptRepo) IncrementAttempts(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAttempts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFailedLoginAttemptRepo_IncrementAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementAttempts'
type MockFailedLoginAttemptRepo_IncrementAttempts_Call struct {
	*mock.Call
}

// IncrementAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockFailedLoginAttemptRepo_Expecter) IncrementAttempts(ctx any, userID any) *MockFailedLoginAttemptRepo_IncrementAttempts_Call {
	return &MockFailedLoginAttemptRepo_IncrementAttempts_Call{Call: _e.mock.On("IncrementAttempts", ctx, userID)}
}

func (_c *MockFailedLoginAttemptRepo_IncrementAttempts_Call) Run(run func(ctx context.Context, userID int)) *MockFailedLoginAttemptRepo_IncrementAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFailedLoginAttemptRepo_IncrementAttempts_Call) Return(err error) *MockFailedLoginAttemptRepo_IncrementAttempts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFailedLoginAttemptRepo_IncrementAttempts_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockFailedLoginAttemptRepo_IncrementAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// IsLocked provides a mock function for the type MockFailedLoginAttemptRepo
func (_mock *MockFailedLoginAttemptRepo) IsLocked(ctx context.Context, userID int) (bool, *time.Time, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsLocked")
	}

	var r0 bool
	var r1 *time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, *time.Time, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) *time.Time); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFailedLoginAttemptRepo_IsLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLocked'
type MockFailedLoginAttemptRepo_IsLocked_Call struct {
	*mock.Call
}

// IsLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockFailedLoginAttemptRepo_Expecter) IsLocked(ctx any, userID any) *MockFailedLoginAttemptRepo_IsLocked_Call {
	return &MockFailedLoginAttemptRepo_IsLocked_Call{Call: _e.mock.On("IsLocked", ctx, userID)}
}

func (_c *MockFailedLoginAttemptRepo_IsLocked_Call) Run(run func(ctx context.Context, userID int)) *MockFailedLoginAttemptRepo_IsLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFailedLoginAttemptRepo_IsLocked_Call) Return(b bool, time1 *time.Time, err error) *MockFailedLoginAttemptRepo_IsLocked_Call {
	_c.Call.Return(b, time1, err)
	return _c
}

func (_c *MockFailedLoginAttemptRepo_IsLocked_Call) RunAndReturn(run func(ctx context.Context, userID int) (bool, *time.Time, error)) *MockFailedLoginAttemptRepo_IsLocked_Call {
	_c.Call.Return(run)
	return _c
}

// LockAccount provides a mock function for the type MockFailedLoginAttemptRepo
func (_mock *MockFailedLoginAttemptRepo) LockAccount(ctx context.Context, userID int, lockoutDuration time.Duration) error {
	ret := _mock.Called(ctx, userID, lockoutDuration)

	if len(ret) == 0 {
		panic("no return value specified for LockAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) error); ok {
		r0 = returnFunc(ctx, userID, lockoutDuration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFailedLoginAttemptRepo_LockAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockAccount'
type MockFailedLoginAttemptRepo_LockAccount_Call struct {
	*mock.Call
}

// LockAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - lockoutDuration time.Duration
func (_e *MockFailedLoginAttemptRepo_Expecter) LockAccount(ctx any, userID any, lockoutDuration any) *MockFailedLoginAttemptRepo_LockAccount_Call {
	return &MockFailedLoginAttemptRepo_LockAccount_Call{Call: _e.mock.On("LockAccount", ctx, userID, lockoutDuration)}
}

func (_c *MockFailedLoginAttemptRepo_LockAccount_Call) Run(run func(ctx context.Context, userID int, lockoutDuration time.Duration)) *MockFailedLoginAttemptRepo_LockAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFailedLoginAttemptRepo_LockAccount_Call) Return(err error) *MockFailedLoginAttemptRepo_LockAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFailedLoginAttemptRepo_LockAccount_Call) RunAndReturn(run func(ctx context.Context, userID int, lockoutDuration time.Duration) error) *MockFailedLoginAttemptRepo_LockAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ResetAttempts provides a mock function for the type MockFailedLoginAttemptRepo
func (_mock *MockFailedLoginAttemptRepo) ResetAttempts(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResetAttempts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFailedLoginAttemptRepo_ResetAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetAttempts'
type MockFailedLoginAttemptRepo_ResetAttempts_Call struct {
	*mock.Call
}

// ResetAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockFailedLoginAttemptRepo_Expecter) ResetAttempts(ctx any, userID any) *MockFailedLoginAttemptRepo_ResetAttempts_Call {
	return &MockFailedLoginAttemptRepo_ResetAttempts_Call{Call: _e.mock.On("ResetAttempts", ctx, userID)}
}

func (_c *MockFailedLoginAttemptRepo_ResetAttempts_Call) Run(run func(ctx context.Context, userID int)) *MockFailedLoginAttemptRepo_ResetAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFailedLoginAttemptRepo_ResetAttempts_Call) Return(err error) *MockFailedLoginAttemptRepo_ResetAttempts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFailedLoginAttemptRepo_ResetAttempts_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockFailedLoginAttemptRepo_ResetAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldSendLockoutEmail provides a mock function for the type MockFailedLoginAttemptRepo
func (_mock *MockFailedLoginAttemptRepo) ShouldSendLockoutEmail(ctx context.Context, userID int, minInterval time.Duration) (bool, error) {
	ret := _mock.Called(ctx, userID, minInterval)

	if len(ret) == 0 {
		panic("no return value specified for ShouldSendLockoutEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, userID, minInterval)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) bool); ok {
		r0 = returnFunc(ctx, userID, minInterval)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, userID, minInterval)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldSendLockoutEmail'
type MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call struct {
	*mock.Call
}

// ShouldSendLockoutEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - minInterval time.Duration
func (_e *MockFailedLoginAttemptRepo_Expecter) ShouldSendLockoutEmail(ctx any, userID any, minInterval any) *MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call {
	return &MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call{Call: _e.mock.On("ShouldSendLockoutEmail", ctx, userID, minInterval)}
}

func (_c *MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call) Run(run func(ctx context.Context, userID int, minInterval time.Duration)) *MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call) Return(b bool, err error) *MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call) RunAndReturn(run func(ctx context.Context, userID int, minInterval time.Duration) (bool, error)) *MockFailedLoginAttemptRepo_ShouldSendLockoutEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastEmailSent provides a mock function for the type MockFailedLoginAttemptRepo
func (_mock *MockFailedLoginAttemptRepo) UpdateLastEmailSent(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastEmailSent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastEmailSent'
type MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call struct {
	*mock.Call
}

// UpdateLastEmailSent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockFailedLoginAttemptRepo_Expecter) UpdateLastEmailSent(ctx any, userID any) *MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call {
	return &MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call{Call: _e.mock.On("UpdateLastEmailSent", ctx, userID)}
}

func (_c *MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call) Run(run func(ctx context.Context, userID int)) *MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call) Return(err error) *MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockFailedLoginAttemptRepo_UpdateLastEmailSent_Call {
	_c.Call.Return(run)
	return _c
}
