// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSoftDeleteRepo creates a new instance of MockSoftDeleteRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSoftDeleteRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSoftDeleteRepo {
	mock := &MockSoftDeleteRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSoftDeleteRepo is an autogenerated mock type for the SoftDeleteRepo type
type MockSoftDeleteRepo struct {
	mock.Mock
}

type MockSoftDeleteRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSoftDeleteRepo) EXPECT() *MockSoftDeleteRepo_Expecter {
	return &MockSoftDeleteRepo_Expecter{mock: &_m.Mock}
}

// GetSoftDeletedContentByID provides a mock function for the type MockSoftDeleteRepo
func (_mock *MockSoftDeleteRepo) GetSoftDeletedContentByID(ctx context.Context, id int) (*repository.SoftDeletedContent, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSoftDeletedContentByID")
	}

	var r0 *repository.SoftDeletedContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*repository.SoftDeletedContent, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *repository.SoftDeletedContent); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.SoftDeletedContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSoftDeleteRepo_GetSoftDeletedContentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSoftDeletedContentByID'
type MockSoftDeleteRepo_GetSoftDeletedContentByID_Call struct {
	*mock.Call
}

// GetSoftDeletedContentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockSoftDeleteRepo_Expecter) GetSoftDeletedContentByID(ctx any, id any) *MockSoftDeleteRepo_GetSoftDeletedContentByID_Call {
	return &MockSoftDeleteRepo_GetSoftDeletedContentByID_Call{Call: _e.mock.On("GetSoftDeletedContentByID", ctx, id)}
}

func (_c *MockSoftDeleteRepo_GetSoftDeletedContentByID_Call) Run(run func(ctx context.Context, id int)) *MockSoftDeleteRepo_GetSoftDeletedContentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSoftDeleteRepo_GetSoftDeletedContentByID_Call) Return(softDeletedContent *repository.SoftDeletedContent, err error) *MockSoftDeleteRepo_GetSoftDeletedContentByID_Call {
	_c.Call.Return(softDeletedContent, err)
	return _c
}

func (_c *MockSoftDeleteRepo_GetSoftDeletedContentByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*repository.SoftDeletedContent, error)) *MockSoftDeleteRepo_GetSoftDeletedContentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSoftDeletedContentByUser provides a mock function for the type MockSoftDeleteRepo
func (_mock *MockSoftDeleteRepo) GetSoftDeletedContentByUser(ctx context.Context, userID int) ([]*repository.SoftDeletedContent, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSoftDeletedContentByUser")
	}

	var r0 []*repository.SoftDeletedContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*repository.SoftDeletedContent, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*repository.SoftDeletedContent); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.SoftDeletedContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSoftDeletedContentByUser'
type MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call struct {
	*mock.Call
}

// GetSoftDeletedContentByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockSoftDeleteRepo_Expecter) GetSoftDeletedContentByUser(ctx any, userID any) *MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call {
	return &MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call{Call: _e.mock.On("GetSoftDeletedContentByUser", ctx, userID)}
}

func (_c *MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call) Run(run func(ctx context.Context, userID int)) *MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call) Return(softDeletedContents []*repository.SoftDeletedContent, err error) *MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call {
	_c.Call.Return(softDeletedContents, err)
	return _c
}

func (_c *MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*repository.SoftDeletedContent, error)) *MockSoftDeleteRepo_GetSoftDeletedContentByUser_Call {
	_c.Call.Return(run)
	return _c
}

// PermanentDeleteContent provides a mock function for the type MockSoftDeleteRepo
func (_mock *MockSoftDeleteRepo) PermanentDeleteContent(ctx context.Context, contentType string, contentID int) error {
	ret := _mock.Called(ctx, contentType, contentID)

	if len(ret) == 0 {
		panic("no return value specified for PermanentDeleteContent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, contentType, contentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSoftDeleteRepo_PermanentDeleteContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PermanentDeleteContent'
type MockSoftDeleteRepo_PermanentDeleteContent_Call struct {
	*mock.Call
}

// PermanentDeleteContent is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - contentID int
func (_e *MockSoftDeleteRepo_Expecter) PermanentDeleteContent(ctx any, contentType any, contentID any) *MockSoftDeleteRepo_PermanentDeleteContent_Call {
	return &MockSoftDeleteRepo_PermanentDeleteContent_Call{Call: _e.mock.On("PermanentDeleteContent", ctx, contentType, contentID)}
}

func (_c *MockSoftDeleteRepo_PermanentDeleteContent_Call) Run(run func(ctx context.Context, contentType string, contentID int)) *MockSoftDeleteRepo_PermanentDeleteContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSoftDeleteRepo_PermanentDeleteContent_Call) Return(err error) *MockSoftDeleteRepo_PermanentDeleteContent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSoftDeleteRepo_PermanentDeleteContent_Call) RunAndReturn(run func(ctx context.Context, contentType string, contentID int) error) *MockSoftDeleteRepo_PermanentDeleteContent_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreContent provides a mock function for the type MockSoftDeleteRepo
func (_mock *MockSoftDeleteRepo) RestoreContent(ctx context.Context, contentType string, contentID int) error {
	ret := _mock.Called(ctx, contentType, contentID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreContent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, contentType, contentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSoftDeleteRepo_RestoreContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreContent'
type MockSoftDeleteRepo_RestoreContent_Call struct {
	*mock.Call
}

// RestoreContent is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - contentID int
func (_e *MockSoftDeleteRepo_Expecter) RestoreContent(ctx any, contentType any, contentID any) *MockSoftDeleteRepo_RestoreContent_Call {
	return &MockSoftDeleteRepo_RestoreContent_Call{Call: _e.mock.On("RestoreContent", ctx, contentType, contentID)}
}

func (_c *MockSoftDeleteRepo_RestoreContent_Call) Run(run func(ctx context.Context, contentType string, contentID int)) *MockSoftDeleteRepo_RestoreContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSoftDeleteRepo_RestoreContent_Call) Return(err error) *MockSoftDeleteRepo_RestoreContent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSoftDeleteRepo_RestoreContent_Call) RunAndReturn(run func(ctx context.Context, contentType string, contentID int) error) *MockSoftDeleteRepo_RestoreContent_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteContent provides a mock function for the type MockSoftDeleteRepo
func (_mock *MockSoftDeleteRepo) SoftDeleteContent(ctx context.Context, contentType string, contentID int, userID int, deletedBy int, reason string) error {
	ret := _mock.Called(ctx, contentType, contentID, userID, deletedBy, reason)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteContent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, int, string) error); ok {
		r0 = returnFunc(ctx, contentType, contentID, userID, deletedBy, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSoftDeleteRepo_SoftDeleteContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteContent'
type MockSoftDeleteRepo_SoftDeleteContent_Call struct {
	*mock.Call
}

// SoftDeleteContent is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - contentID int
//   - userID int
//   - deletedBy int
//   - reason string
func (_e *MockSoftDeleteRepo_Expecter) SoftDeleteContent(ctx any, contentType any, contentID any, userID any, deletedBy any, reason any) *MockSoftDeleteRepo_SoftDeleteContent_Call {
	return &MockSoftDeleteRepo_SoftDeleteContent_Call{Call: _e.mock.On("SoftDeleteContent", ctx, contentType, contentID, userID, deletedBy, reason)}
}

func (_c *MockSoftDeleteRepo_SoftDeleteContent_Call) Run(run func(ctx context.Context, contentType string, contentID int, userID int, deletedBy int, reason string)) *MockSoftDeleteRepo_SoftDeleteContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSoftDeleteRepo_SoftDeleteContent_Call) Return(err error) *MockSoftDeleteRepo_SoftDeleteContent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSoftDeleteRepo_SoftDeleteContent_Call) RunAndReturn(run func(ctx context.Context, contentType string, contentID int, userID int, deletedBy int, reason string) error) *MockSoftDeleteRepo_SoftDeleteContent_Call {
	_c.Call.Return(run)
	return _c
}
