// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// CheckEmailExists provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckEmailExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CheckEmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckEmailExists'
type MockUserRepo_CheckEmailExists_Call struct {
	*mock.Call
}

// CheckEmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepo_Expecter) CheckEmailExists(ctx any, email any) *MockUserRepo_CheckEmailExists_Call {
	return &MockUserRepo_CheckEmailExists_Call{Call: _e.mock.On("CheckEmailExists", ctx, email)}
}

func (_c *MockUserRepo_CheckEmailExists_Call) Run(run func(ctx context.Context, email string)) *MockUserRepo_CheckEmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_CheckEmailExists_Call) Return(b bool, err error) *MockUserRepo_CheckEmailExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepo_CheckEmailExists_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockUserRepo_CheckEmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// CheckEmailExistsForOtherUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CheckEmailExistsForOtherUser(ctx context.Context, userID int, email string) (bool, error) {
	ret := _mock.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckEmailExistsForOtherUser")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (bool, error)); ok {
		return returnFunc(ctx, userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) bool); ok {
		r0 = returnFunc(ctx, userID, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, userID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CheckEmailExistsForOtherUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckEmailExistsForOtherUser'
type MockUserRepo_CheckEmailExistsForOtherUser_Call struct {
	*mock.Call
}

// CheckEmailExistsForOtherUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - email string
func (_e *MockUserRepo_Expecter) CheckEmailExistsForOtherUser(ctx any, userID any, email any) *MockUserRepo_CheckEmailExistsForOtherUser_Call {
	return &MockUserRepo_CheckEmailExistsForOtherUser_Call{Call: _e.mock.On("CheckEmailExistsForOtherUser", ctx, userID, email)}
}

func (_c *MockUserRepo_CheckEmailExistsForOtherUser_Call) Run(run func(ctx context.Context, userID int, email string)) *MockUserRepo_CheckEmailExistsForOtherUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_CheckEmailExistsForOtherUser_Call) Return(b bool, err error) *MockUserRepo_CheckEmailExistsForOtherUser_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepo_CheckEmailExistsForOtherUser_Call) RunAndReturn(run func(ctx context.Context, userID int, email string) (bool, error)) *MockUserRepo_CheckEmailExistsForOtherUser_Call {
	_c.Call.Return(run)
	return _c
}

// CheckUsernameExists provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for CheckUsernameExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CheckUsernameExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUsernameExists'
type MockUserRepo_CheckUsernameExists_Call struct {
	*mock.Call
}

// CheckUsernameExists is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepo_Expecter) CheckUsernameExists(ctx any, username any) *MockUserRepo_CheckUsernameExists_Call {
	return &MockUserRepo_CheckUsernameExists_Call{Call: _e.mock.On("CheckUsernameExists", ctx, username)}
}

func (_c *MockUserRepo_CheckUsernameExists_Call) Run(run func(ctx context.Context, username string)) *MockUserRepo_CheckUsernameExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_CheckUsernameExists_Call) Return(b bool, err error) *MockUserRepo_CheckUsernameExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepo_CheckUsernameExists_Call) RunAndReturn(run func(ctx context.Context, username string) (bool, error)) *MockUserRepo_CheckUsernameExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateUser(ctx context.Context, user *repository.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *repository.User
func (_e *MockUserRepo_Expecter) CreateUser(ctx any, user any) *MockUserRepo_CreateUser_Call {
	return &MockUserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserRepo_CreateUser_Call) Run(run func(ctx context.Context, user *repository.User)) *MockUserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.User
		if args[1] != nil {
			arg1 = args[1].(*repository.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) Return(err error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *repository.User) error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProfilePicture provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) DeleteProfilePicture(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfilePicture")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_DeleteProfilePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfilePicture'
type MockUserRepo_DeleteProfilePicture_Call struct {
	*mock.Call
}

// DeleteProfilePicture is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) DeleteProfilePicture(ctx any, userID any) *MockUserRepo_DeleteProfilePicture_Call {
	return &MockUserRepo_DeleteProfilePicture_Call{Call: _e.mock.On("DeleteProfilePicture", ctx, userID)}
}

func (_c *MockUserRepo_DeleteProfilePicture_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_DeleteProfilePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_DeleteProfilePicture_Call) Return(err error) *MockUserRepo_DeleteProfilePicture_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_DeleteProfilePicture_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_DeleteProfilePicture_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) DeleteUser(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserRepo_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) DeleteUser(ctx any, userID any) *MockUserRepo_DeleteUser_Call {
	return &MockUserRepo_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID)}
}

func (_c *MockUserRepo_DeleteUser_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_DeleteUser_Call) Return(err error) *MockUserRepo_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAdminUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetAdminUser(ctx context.Context) (*repository.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminUser")
	}

	var r0 *repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*repository.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *repository.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetAdminUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminUser'
type MockUserRepo_GetAdminUser_Call struct {
	*mock.Call
}

// GetAdminUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepo_Expecter) GetAdminUser(ctx any) *MockUserRepo_GetAdminUser_Call {
	return &MockUserRepo_GetAdminUser_Call{Call: _e.mock.On("GetAdminUser", ctx)}
}

func (_c *MockUserRepo_GetAdminUser_Call) Run(run func(ctx context.Context)) *MockUserRepo_GetAdminUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetAdminUser_Call) Return(user *repository.User, err error) *MockUserRepo_GetAdminUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetAdminUser_Call) RunAndReturn(run func(ctx context.Context) (*repository.User, error)) *MockUserRepo_GetAdminUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetAllUsers(ctx context.Context, status string, limit int, offset int) ([]*repository.User, error) {
	ret := _mock.Called(ctx, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*repository.User, error)); ok {
		return returnFunc(ctx, status, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*repository.User); ok {
		r0 = returnFunc(ctx, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserRepo_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - limit int
//   - offset int
func (_e *MockUserRepo_Expecter) GetAllUsers(ctx any, status any, limit any, offset any) *MockUserRepo_GetAllUsers_Call {
	return &MockUserRepo_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx, status, limit, offset)}
}

func (_c *MockUserRepo_GetAllUsers_Call) Run(run func(ctx context.Context, status string, limit int, offset int)) *MockUserRepo_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetAllUsers_Call) Return(users []*repository.User, err error) *MockUserRepo_GetAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepo_GetAllUsers_Call) RunAndReturn(run func(ctx context.Context, status string, limit int, offset int) ([]*repository.User, error)) *MockUserRepo_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingUsers provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetPendingUsers(ctx context.Context, limit int, offset int) ([]*repository.User, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingUsers")
	}

	var r0 []*repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*repository.User, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*repository.User); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetPendingUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingUsers'
type MockUserRepo_GetPendingUsers_Call struct {
	*mock.Call
}

// GetPendingUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockUserRepo_Expecter) GetPendingUsers(ctx any, limit any, offset any) *MockUserRepo_GetPendingUsers_Call {
	return &MockUserRepo_GetPendingUsers_Call{Call: _e.mock.On("GetPendingUsers", ctx, limit, offset)}
}

func (_c *MockUserRepo_GetPendingUsers_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockUserRepo_GetPendingUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetPendingUsers_Call) Return(users []*repository.User, err error) *MockUserRepo_GetPendingUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepo_GetPendingUsers_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*repository.User, error)) *MockUserRepo_GetPendingUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByEmail(ctx context.Context, email string) (*repository.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserRepo_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepo_Expecter) GetUserByEmail(ctx any, email any) *MockUserRepo_GetUserByEmail_Call {
	return &MockUserRepo_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserRepo_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepo_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserByEmail_Call) Return(user *repository.User, err error) *MockUserRepo_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*repository.User, error)) *MockUserRepo_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByID(ctx context.Context, userID int) (*repository.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*repository.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *repository.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepo_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) GetUserByID(ctx any, userID any) *MockUserRepo_GetUserByID_Call {
	return &MockUserRepo_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserRepo_GetUserByID_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) Return(user *repository.User, err error) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID int) (*repository.User, error)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByUsername(ctx context.Context, username string) (*repository.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUserRepo_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepo_Expecter) GetUserByUsername(ctx any, username any) *MockUserRepo_GetUserByUsername_Call {
	return &MockUserRepo_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUserRepo_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepo_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserByUsername_Call) Return(user *repository.User, err error) *MockUserRepo_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*repository.User, error)) *MockUserRepo_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserStatus provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserStatus(ctx context.Context, userID int) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserStatus'
type MockUserRepo_GetUserStatus_Call struct {
	*mock.Call
}

// GetUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) GetUserStatus(ctx any, userID any) *MockUserRepo_GetUserStatus_Call {
	return &MockUserRepo_GetUserStatus_Call{Call: _e.mock.On("GetUserStatus", ctx, userID)}
}

func (_c *MockUserRepo_GetUserStatus_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_GetUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserStatus_Call) Return(s string, err error) *MockUserRepo_GetUserStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserRepo_GetUserStatus_Call) RunAndReturn(run func(ctx context.Context, userID int) (string, error)) *MockUserRepo_GetUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) SoftDeleteUser(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_SoftDeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteUser'
type MockUserRepo_SoftDeleteUser_Call struct {
	*mock.Call
}

// SoftDeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) SoftDeleteUser(ctx any, userID any) *MockUserRepo_SoftDeleteUser_Call {
	return &MockUserRepo_SoftDeleteUser_Call{Call: _e.mock.On("SoftDeleteUser", ctx, userID)}
}

func (_c *MockUserRepo_SoftDeleteUser_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_SoftDeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_SoftDeleteUser_Call) Return(err error) *MockUserRepo_SoftDeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_SoftDeleteUser_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_SoftDeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// SuspendUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) SuspendUser(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SuspendUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_SuspendUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuspendUser'
type MockUserRepo_SuspendUser_Call struct {
	*mock.Call
}

// SuspendUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) SuspendUser(ctx any, userID any) *MockUserRepo_SuspendUser_Call {
	return &MockUserRepo_SuspendUser_Call{Call: _e.mock.On("SuspendUser", ctx, userID)}
}

func (_c *MockUserRepo_SuspendUser_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_SuspendUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_SuspendUser_Call) Return(err error) *MockUserRepo_SuspendUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_SuspendUser_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_SuspendUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnsuspendUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UnsuspendUser(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnsuspendUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UnsuspendUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsuspendUser'
type MockUserRepo_UnsuspendUser_Call struct {
	*mock.Call
}

// UnsuspendUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) UnsuspendUser(ctx any, userID any) *MockUserRepo_UnsuspendUser_Call {
	return &MockUserRepo_UnsuspendUser_Call{Call: _e.mock.On("UnsuspendUser", ctx, userID)}
}

func (_c *MockUserRepo_UnsuspendUser_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_UnsuspendUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_UnsuspendUser_Call) Return(err error) *MockUserRepo_UnsuspendUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UnsuspendUser_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_UnsuspendUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAdminPasswordAndEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateAdminPasswordAndEmail(ctx context.Context, passwordHash string, email string, currentPasswordHash string) error {
	ret := _mock.Called(ctx, passwordHash, email, currentPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAdminPasswordAndEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, passwordHash, email, currentPasswordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateAdminPasswordAndEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAdminPasswordAndEmail'
type MockUserRepo_UpdateAdminPasswordAndEmail_Call struct {
	*mock.Call
}

// UpdateAdminPasswordAndEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - passwordHash string
//   - email string
//   - currentPasswordHash string
func (_e *MockUserRepo_Expecter) UpdateAdminPasswordAndEmail(ctx any, passwordHash any, email any, currentPasswordHash any) *MockUserRepo_UpdateAdminPasswordAndEmail_Call {
	return &MockUserRepo_UpdateAdminPasswordAndEmail_Call{Call: _e.mock.On("UpdateAdminPasswordAndEmail", ctx, passwordHash, email, currentPasswordHash)}
}

func (_c *MockUserRepo_UpdateAdminPasswordAndEmail_Call) Run(run func(ctx context.Context, passwordHash string, email string, currentPasswordHash string)) *MockUserRepo_UpdateAdminPasswordAndEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateAdminPasswordAndEmail_Call) Return(err error) *MockUserRepo_UpdateAdminPasswordAndEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateAdminPasswordAndEmail_Call) RunAndReturn(run func(ctx context.Context, passwordHash string, email string, currentPasswordHash string) error) *MockUserRepo_UpdateAdminPasswordAndEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCustomFields provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateCustomFields(ctx context.Context, userID int, customFields map[string]any) error {
	ret := _mock.Called(ctx, userID, customFields)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomFields")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, map[string]any) error); ok {
		r0 = returnFunc(ctx, userID, customFields)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateCustomFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCustomFields'
type MockUserRepo_UpdateCustomFields_Call struct {
	*mock.Call
}

// UpdateCustomFields is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - customFields map[string]any
func (_e *MockUserRepo_Expecter) UpdateCustomFields(ctx any, userID any, customFields any) *MockUserRepo_UpdateCustomFields_Call {
	return &MockUserRepo_UpdateCustomFields_Call{Call: _e.mock.On("UpdateCustomFields", ctx, userID, customFields)}
}

func (_c *MockUserRepo_UpdateCustomFields_Call) Run(run func(ctx context.Context, userID int, customFields map[string]any)) *MockUserRepo_UpdateCustomFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateCustomFields_Call) Return(err error) *MockUserRepo_UpdateCustomFields_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateCustomFields_Call) RunAndReturn(run func(ctx context.Context, userID int, customFields map[string]any) error) *MockUserRepo_UpdateCustomFields_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateEmail(ctx context.Context, userID int, email string) error {
	ret := _mock.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmail'
type MockUserRepo_UpdateEmail_Call struct {
	*mock.Call
}

// UpdateEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - email string
func (_e *MockUserRepo_Expecter) UpdateEmail(ctx any, userID any, email any) *MockUserRepo_UpdateEmail_Call {
	return &MockUserRepo_UpdateEmail_Call{Call: _e.mock.On("UpdateEmail", ctx, userID, email)}
}

func (_c *MockUserRepo_UpdateEmail_Call) Run(run func(ctx context.Context, userID int, email string)) *MockUserRepo_UpdateEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateEmail_Call) Return(err error) *MockUserRepo_UpdateEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateEmail_Call) RunAndReturn(run func(ctx context.Context, userID int, email string) error) *MockUserRepo_UpdateEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastLoginAt provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateLastLoginAt(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastLoginAt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateLastLoginAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastLoginAt'
type MockUserRepo_UpdateLastLoginAt_Call struct {
	*mock.Call
}

// UpdateLastLoginAt is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) UpdateLastLoginAt(ctx any, userID any) *MockUserRepo_UpdateLastLoginAt_Call {
	return &MockUserRepo_UpdateLastLoginAt_Call{Call: _e.mock.On("UpdateLastLoginAt", ctx, userID)}
}

func (_c *MockUserRepo_UpdateLastLoginAt_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_UpdateLastLoginAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateLastLoginAt_Call) Return(err error) *MockUserRepo_UpdateLastLoginAt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateLastLoginAt_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_UpdateLastLoginAt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdatePassword(ctx context.Context, userID int, currentPasswordHash string, newPasswordHash string) error {
	ret := _mock.Called(ctx, userID, currentPasswordHash, newPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, userID, currentPasswordHash, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockUserRepo_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - currentPasswordHash string
//   - newPasswordHash string
func (_e *MockUserRepo_Expecter) UpdatePassword(ctx any, userID any, currentPasswordHash any, newPasswordHash any) *MockUserRepo_UpdatePassword_Call {
	return &MockUserRepo_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, currentPasswordHash, newPasswordHash)}
}

func (_c *MockUserRepo_UpdatePassword_Call) Run(run func(ctx context.Context, userID int, currentPasswordHash string, newPasswordHash string)) *MockUserRepo_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdatePassword_Call) Return(err error) *MockUserRepo_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, userID int, currentPasswordHash string, newPasswordHash string) error) *MockUserRepo_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasswordByUserID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdatePasswordByUserID(ctx context.Context, userID int, newPasswordHash string) error {
	ret := _mock.Called(ctx, userID, newPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdatePasswordByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasswordByUserID'
type MockUserRepo_UpdatePasswordByUserID_Call struct {
	*mock.Call
}

// UpdatePasswordByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - newPasswordHash string
func (_e *MockUserRepo_Expecter) UpdatePasswordByUserID(ctx any, userID any, newPasswordHash any) *MockUserRepo_UpdatePasswordByUserID_Call {
	return &MockUserRepo_UpdatePasswordByUserID_Call{Call: _e.mock.On("UpdatePasswordByUserID", ctx, userID, newPasswordHash)}
}

func (_c *MockUserRepo_UpdatePasswordByUserID_Call) Run(run func(ctx context.Context, userID int, newPasswordHash string)) *MockUserRepo_UpdatePasswordByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdatePasswordByUserID_Call) Return(err error) *MockUserRepo_UpdatePasswordByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdatePasswordByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int, newPasswordHash string) error) *MockUserRepo_UpdatePasswordByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateProfile(ctx context.Context, userID int, name string, email string, role string, customFields map[string]any) error {
	ret := _mock.Called(ctx, userID, name, email, role, customFields)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string, string, map[string]any) error); ok {
		r0 = returnFunc(ctx, userID, name, email, role, customFields)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserRepo_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - name string
//   - email string
//   - role string
//   - customFields map[string]any
func (_e *MockUserRepo_Expecter) UpdateProfile(ctx any, userID any, name any, email any, role any, customFields any) *MockUserRepo_UpdateProfile_Call {
	return &MockUserRepo_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, name, email, role, customFields)}
}

func (_c *MockUserRepo_UpdateProfile_Call) Run(run func(ctx context.Context, userID int, name string, email string, role string, customFields map[string]any)) *MockUserRepo_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 map[string]any
		if args[5] != nil {
			arg5 = args[5].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateProfile_Call) Return(err error) *MockUserRepo_UpdateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, userID int, name string, email string, role string, customFields map[string]any) error) *MockUserRepo_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfilePicture provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateProfilePicture(ctx context.Context, userID int, profilePicture string) error {
	ret := _mock.Called(ctx, userID, profilePicture)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfilePicture")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, profilePicture)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateProfilePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfilePicture'
type MockUserRepo_UpdateProfilePicture_Call struct {
	*mock.Call
}

// UpdateProfilePicture is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - profilePicture string
func (_e *MockUserRepo_Expecter) UpdateProfilePicture(ctx any, userID any, profilePicture any) *MockUserRepo_UpdateProfilePicture_Call {
	return &MockUserRepo_UpdateProfilePicture_Call{Call: _e.mock.On("UpdateProfilePicture", ctx, userID, profilePicture)}
}

func (_c *MockUserRepo_UpdateProfilePicture_Call) Run(run func(ctx context.Context, userID int, profilePicture string)) *MockUserRepo_UpdateProfilePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateProfilePicture_Call) Return(err error) *MockUserRepo_UpdateProfilePicture_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateProfilePicture_Call) RunAndReturn(run func(ctx context.Context, userID int, profilePicture string) error) *MockUserRepo_UpdateProfilePicture_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStatus provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateUserStatus(ctx context.Context, userID int, status string) error {
	ret := _mock.Called(ctx, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStatus'
type MockUserRepo_UpdateUserStatus_Call struct {
	*mock.Call
}

// UpdateUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - status string
func (_e *MockUserRepo_Expecter) UpdateUserStatus(ctx any, userID any, status any) *MockUserRepo_UpdateUserStatus_Call {
	return &MockUserRepo_UpdateUserStatus_Call{Call: _e.mock.On("UpdateUserStatus", ctx, userID, status)}
}

func (_c *MockUserRepo_UpdateUserStatus_Call) Run(run func(ctx context.Context, userID int, status string)) *MockUserRepo_UpdateUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateUserStatus_Call) Return(err error) *MockUserRepo_UpdateUserStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateUserStatus_Call) RunAndReturn(run func(ctx context.Context, userID int, status string) error) *MockUserRepo_UpdateUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStatusIfCurrentStatus provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateUserStatusIfCurrentStatus(ctx context.Context, userID int, currentStatus string, newStatus string) error {
	ret := _mock.Called(ctx, userID, currentStatus, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatusIfCurrentStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, userID, currentStatus, newStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateUserStatusIfCurrentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStatusIfCurrentStatus'
type MockUserRepo_UpdateUserStatusIfCurrentStatus_Call struct {
	*mock.Call
}

// UpdateUserStatusIfCurrentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - currentStatus string
//   - newStatus string
func (_e *MockUserRepo_Expecter) UpdateUserStatusIfCurrentStatus(ctx any, userID any, currentStatus any, newStatus any) *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call {
	return &MockUserRepo_UpdateUserStatusIfCurrentStatus_Call{Call: _e.mock.On("UpdateUserStatusIfCurrentStatus", ctx, userID, currentStatus, newStatus)}
}

func (_c *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call) Run(run func(ctx context.Context, userID int, currentStatus string, newStatus string)) *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call) Return(err error) *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call) RunAndReturn(run func(ctx context.Context, userID int, currentStatus string, newStatus string) error) *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call {
	_c.Call.Return(run)
	return _c
}
