// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserLookup creates a new instance of MockUserLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserLookup {
	mock := &MockUserLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserLookup is an autogenerated mock type for the UserLookup type
type MockUserLookup struct {
	mock.Mock
}

type MockUserLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserLookup) EXPECT() *MockUserLookup_Expecter {
	return &MockUserLookup_Expecter{mock: &_m.Mock}
}

// GetUserByID provides a mock function for the type MockUserLookup
func (_mock *MockUserLookup) GetUserByID(ctx context.Context, userID int) (*repository.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*repository.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *repository.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserLookup_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserLookup_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserLookup_Expecter) GetUserByID(ctx any, userID any) *MockUserLookup_GetUserByID_Call {
	return &MockUserLookup_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserLookup_GetUserByID_Call) Run(run func(ctx context.Context, userID int)) *MockUserLookup_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserLookup_GetUserByID_Call) Return(user *repository.User, err error) *MockUserLookup_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserLookup_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID int) (*repository.User, error)) *MockUserLookup_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}
