// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/content"
	mock "github.com/stretchr/testify/mock"
)

// newMockcontentCreator creates a new instance of mockcontentCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcontentCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcontentCreator {
	mock := &mockcontentCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcontentCreator is an autogenerated mock type for the contentCreator type
type mockcontentCreator struct {
	mock.Mock
}

type mockcontentCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcontentCreator) EXPECT() *mockcontentCreator_Expecter {
	return &mockcontentCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockcontentCreator
func (_mock *mockcontentCreator) Create(ctx context.Context, userID int, req content.CreateContentRequest) (*content.Content, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, content.CreateContentRequest) (*content.Content, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, content.CreateContentRequest) *content.Content); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, content.CreateContentRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcontentCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockcontentCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - req content.CreateContentRequest
func (_e *mockcontentCreator_Expecter) Create(ctx any, userID any, req any) *mockcontentCreator_Create_Call {
	return &mockcontentCreator_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *mockcontentCreator_Create_Call) Run(run func(ctx context.Context, userID int, req content.CreateContentRequest)) *mockcontentCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 content.CreateContentRequest
		if args[2] != nil {
			arg2 = args[2].(content.CreateContentRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockcontentCreator_Create_Call) Return(content1 *content.Content, err error) *mockcontentCreator_Create_Call {
	_c.Call.Return(content1, err)
	return _c
}

func (_c *mockcontentCreator_Create_Call) RunAndReturn(run func(ctx context.Context, userID int, req content.CreateContentRequest) (*content.Content, error)) *mockcontentCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}
