// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/media"
	mock "github.com/stretchr/testify/mock"
)

// newMockmediaService creates a new instance of mockmediaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmediaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmediaService {
	mock := &mockmediaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockmediaService is an autogenerated mock type for the mediaService type
type mockmediaService struct {
	mock.Mock
}

type mockmediaService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmediaService) EXPECT() *mockmediaService_Expecter {
	return &mockmediaService_Expecter{mock: &_m.Mock}
}

// GenerateFromBytes provides a mock function for the type mockmediaService
func (_mock *mockmediaService) GenerateFromBytes(ctx context.Context, imageBytes []byte, userID int, altText string, originalFilename string) (*media.Media, error) {
	ret := _mock.Called(ctx, imageBytes, userID, altText, originalFilename)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromBytes")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, string, string) (*media.Media, error)); ok {
		return returnFunc(ctx, imageBytes, userID, altText, originalFilename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int, string, string) *media.Media); ok {
		r0 = returnFunc(ctx, imageBytes, userID, altText, originalFilename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, int, string, string) error); ok {
		r1 = returnFunc(ctx, imageBytes, userID, altText, originalFilename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockmediaService_GenerateFromBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFromBytes'
type mockmediaService_GenerateFromBytes_Call struct {
	*mock.Call
}

// GenerateFromBytes is a helper method to define mock.On call
//   - ctx context.Context
//   - imageBytes []byte
//   - userID int
//   - altText string
//   - originalFilename string
func (_e *mockmediaService_Expecter) GenerateFromBytes(ctx any, imageBytes any, userID any, altText any, originalFilename any) *mockmediaService_GenerateFromBytes_Call {
	return &mockmediaService_GenerateFromBytes_Call{Call: _e.mock.On("GenerateFromBytes", ctx, imageBytes, userID, altText, originalFilename)}
}

func (_c *mockmediaService_GenerateFromBytes_Call) Run(run func(ctx context.Context, imageBytes []byte, userID int, altText string, originalFilename string)) *mockmediaService_GenerateFromBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockmediaService_GenerateFromBytes_Call) Return(media1 *media.Media, err error) *mockmediaService_GenerateFromBytes_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *mockmediaService_GenerateFromBytes_Call) RunAndReturn(run func(ctx context.Context, imageBytes []byte, userID int, altText string, originalFilename string) (*media.Media, error)) *mockmediaService_GenerateFromBytes_Call {
	_c.Call.Return(run)
	return _c
}
