// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/aristorinjuang/lesstruct/internal/domain/customfield"
	"github.com/aristorinjuang/lesstruct/internal/domain/posttype"
	mock "github.com/stretchr/testify/mock"
)

// newMockpostTypeLister creates a new instance of mockpostTypeLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockpostTypeLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockpostTypeLister {
	mock := &mockpostTypeLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockpostTypeLister is an autogenerated mock type for the postTypeLister type
type mockpostTypeLister struct {
	mock.Mock
}

type mockpostTypeLister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockpostTypeLister) EXPECT() *mockpostTypeLister_Expecter {
	return &mockpostTypeLister_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type mockpostTypeLister
func (_mock *mockpostTypeLister) GetAll() []posttype.PostType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []posttype.PostType
	if returnFunc, ok := ret.Get(0).(func() []posttype.PostType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]posttype.PostType)
		}
	}
	return r0
}

// mockpostTypeLister_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type mockpostTypeLister_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *mockpostTypeLister_Expecter) GetAll() *mockpostTypeLister_GetAll_Call {
	return &mockpostTypeLister_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *mockpostTypeLister_GetAll_Call) Run(run func()) *mockpostTypeLister_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockpostTypeLister_GetAll_Call) Return(postTypes []posttype.PostType) *mockpostTypeLister_GetAll_Call {
	_c.Call.Return(postTypes)
	return _c
}

func (_c *mockpostTypeLister_GetAll_Call) RunAndReturn(run func() []posttype.PostType) *mockpostTypeLister_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetFieldsByPostType provides a mock function for the type mockpostTypeLister
func (_mock *mockpostTypeLister) GetFieldsByPostType(slug string) ([]customfield.FieldSchema, error) {
	ret := _mock.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for GetFieldsByPostType")
	}

	var r0 []customfield.FieldSchema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]customfield.FieldSchema, error)); ok {
		return returnFunc(slug)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []customfield.FieldSchema); ok {
		r0 = returnFunc(slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customfield.FieldSchema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockpostTypeLister_GetFieldsByPostType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFieldsByPostType'
type mockpostTypeLister_GetFieldsByPostType_Call struct {
	*mock.Call
}

// GetFieldsByPostType is a helper method to define mock.On call
//   - slug string
func (_e *mockpostTypeLister_Expecter) GetFieldsByPostType(slug any) *mockpostTypeLister_GetFieldsByPostType_Call {
	return &mockpostTypeLister_GetFieldsByPostType_Call{Call: _e.mock.On("GetFieldsByPostType", slug)}
}

func (_c *mockpostTypeLister_GetFieldsByPostType_Call) Run(run func(slug string)) *mockpostTypeLister_GetFieldsByPostType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockpostTypeLister_GetFieldsByPostType_Call) Return(fieldSchemas []customfield.FieldSchema, err error) *mockpostTypeLister_GetFieldsByPostType_Call {
	_c.Call.Return(fieldSchemas, err)
	return _c
}

func (_c *mockpostTypeLister_GetFieldsByPostType_Call) RunAndReturn(run func(slug string) ([]customfield.FieldSchema, error)) *mockpostTypeLister_GetFieldsByPostType_Call {
	_c.Call.Return(run)
	return _c
}
