// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// newMockuserResolverRepo creates a new instance of mockuserResolverRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserResolverRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserResolverRepo {
	mock := &mockuserResolverRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserResolverRepo is an autogenerated mock type for the userResolverRepo type
type mockuserResolverRepo struct {
	mock.Mock
}

type mockuserResolverRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserResolverRepo) EXPECT() *mockuserResolverRepo_Expecter {
	return &mockuserResolverRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type mockuserResolverRepo
func (_mock *mockuserResolverRepo) CreateUser(ctx context.Context, user *repository.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockuserResolverRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockuserResolverRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *repository.User
func (_e *mockuserResolverRepo_Expecter) CreateUser(ctx any, user any) *mockuserResolverRepo_CreateUser_Call {
	return &mockuserResolverRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *mockuserResolverRepo_CreateUser_Call) Run(run func(ctx context.Context, user *repository.User)) *mockuserResolverRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.User
		if args[1] != nil {
			arg1 = args[1].(*repository.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserResolverRepo_CreateUser_Call) Return(err error) *mockuserResolverRepo_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockuserResolverRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *repository.User) error) *mockuserResolverRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type mockuserResolverRepo
func (_mock *mockuserResolverRepo) GetUserByEmail(ctx context.Context, email string) (*repository.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserResolverRepo_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type mockuserResolverRepo_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *mockuserResolverRepo_Expecter) GetUserByEmail(ctx any, email any) *mockuserResolverRepo_GetUserByEmail_Call {
	return &mockuserResolverRepo_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *mockuserResolverRepo_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *mockuserResolverRepo_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserResolverRepo_GetUserByEmail_Call) Return(user *repository.User, err error) *mockuserResolverRepo_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserResolverRepo_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*repository.User, error)) *mockuserResolverRepo_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type mockuserResolverRepo
func (_mock *mockuserResolverRepo) GetUserByUsername(ctx context.Context, username string) (*repository.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*repository.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *repository.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserResolverRepo_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type mockuserResolverRepo_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockuserResolverRepo_Expecter) GetUserByUsername(ctx any, username any) *mockuserResolverRepo_GetUserByUsername_Call {
	return &mockuserResolverRepo_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *mockuserResolverRepo_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *mockuserResolverRepo_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserResolverRepo_GetUserByUsername_Call) Return(user *repository.User, err error) *mockuserResolverRepo_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserResolverRepo_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*repository.User, error)) *mockuserResolverRepo_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}
