// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockuserResolver creates a new instance of mockuserResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserResolver {
	mock := &mockuserResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserResolver is an autogenerated mock type for the userResolver type
type mockuserResolver struct {
	mock.Mock
}

type mockuserResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserResolver) EXPECT() *mockuserResolver_Expecter {
	return &mockuserResolver_Expecter{mock: &_m.Mock}
}

// ResolveOrCreate provides a mock function for the type mockuserResolver
func (_mock *mockuserResolver) ResolveOrCreate(ctx context.Context, login string, email string, displayName string) (int, bool, error) {
	ret := _mock.Called(ctx, login, email, displayName)

	if len(ret) == 0 {
		panic("no return value specified for ResolveOrCreate")
	}

	var r0 int
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (int, bool, error)); ok {
		return returnFunc(ctx, login, email, displayName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) int); ok {
		r0 = returnFunc(ctx, login, email, displayName)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) bool); ok {
		r1 = returnFunc(ctx, login, email, displayName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, login, email, displayName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockuserResolver_ResolveOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveOrCreate'
type mockuserResolver_ResolveOrCreate_Call struct {
	*mock.Call
}

// ResolveOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - email string
//   - displayName string
func (_e *mockuserResolver_Expecter) ResolveOrCreate(ctx any, login any, email any, displayName any) *mockuserResolver_ResolveOrCreate_Call {
	return &mockuserResolver_ResolveOrCreate_Call{Call: _e.mock.On("ResolveOrCreate", ctx, login, email, displayName)}
}

func (_c *mockuserResolver_ResolveOrCreate_Call) Run(run func(ctx context.Context, login string, email string, displayName string)) *mockuserResolver_ResolveOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockuserResolver_ResolveOrCreate_Call) Return(userID int, created bool, err error) *mockuserResolver_ResolveOrCreate_Call {
	_c.Call.Return(userID, created, err)
	return _c
}

func (_c *mockuserResolver_ResolveOrCreate_Call) RunAndReturn(run func(ctx context.Context, login string, email string, displayName string) (int, bool, error)) *mockuserResolver_ResolveOrCreate_Call {
	_c.Call.Return(run)
	return _c
}
