// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/alias"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAliasService creates a new instance of MockAliasService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAliasService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAliasService {
	mock := &MockAliasService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAliasService is an autogenerated mock type for the AliasService type
type MockAliasService struct {
	mock.Mock
}

type MockAliasService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAliasService) EXPECT() *MockAliasService_Expecter {
	return &MockAliasService_Expecter{mock: &_m.Mock}
}

// FindByContentID provides a mock function for the type MockAliasService
func (_mock *MockAliasService) FindByContentID(ctx context.Context, contentID int) ([]*alias.Alias, error) {
	ret := _mock.Called(ctx, contentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByContentID")
	}

	var r0 []*alias.Alias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*alias.Alias, error)); ok {
		return returnFunc(ctx, contentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*alias.Alias); ok {
		r0 = returnFunc(ctx, contentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*alias.Alias)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, contentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAliasService_FindByContentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByContentID'
type MockAliasService_FindByContentID_Call struct {
	*mock.Call
}

// FindByContentID is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID int
func (_e *MockAliasService_Expecter) FindByContentID(ctx any, contentID any) *MockAliasService_FindByContentID_Call {
	return &MockAliasService_FindByContentID_Call{Call: _e.mock.On("FindByContentID", ctx, contentID)}
}

func (_c *MockAliasService_FindByContentID_Call) Run(run func(ctx context.Context, contentID int)) *MockAliasService_FindByContentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAliasService_FindByContentID_Call) Return(aliass []*alias.Alias, err error) *MockAliasService_FindByContentID_Call {
	_c.Call.Return(aliass, err)
	return _c
}

func (_c *MockAliasService_FindByContentID_Call) RunAndReturn(run func(ctx context.Context, contentID int) ([]*alias.Alias, error)) *MockAliasService_FindByContentID_Call {
	_c.Call.Return(run)
	return _c
}
