// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/dashboard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function for the type MockRepository
func (_mock *MockRepository) GetStats(ctx context.Context, userID int) (*dashboard.Stats, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *dashboard.Stats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*dashboard.Stats, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *dashboard.Stats); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dashboard.Stats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepository_Expecter) GetStats(ctx any, userID any) *MockRepository_GetStats_Call {
	return &MockRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, userID)}
}

func (_c *MockRepository_GetStats_Call) Run(run func(ctx context.Context, userID int)) *MockRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetStats_Call) Return(stats *dashboard.Stats, err error) *MockRepository_GetStats_Call {
	_c.Call.Return(stats, err)
	return _c
}

func (_c *MockRepository_GetStats_Call) RunAndReturn(run func(ctx context.Context, userID int) (*dashboard.Stats, error)) *MockRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}
