// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountDeletionServiceInterface creates a new instance of MockAccountDeletionServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountDeletionServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountDeletionServiceInterface {
	mock := &MockAccountDeletionServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountDeletionServiceInterface is an autogenerated mock type for the AccountDeletionServiceInterface type
type MockAccountDeletionServiceInterface struct {
	mock.Mock
}

type MockAccountDeletionServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountDeletionServiceInterface) EXPECT() *MockAccountDeletionServiceInterface_Expecter {
	return &MockAccountDeletionServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function for the type MockAccountDeletionServiceInterface
func (_mock *MockAccountDeletionServiceInterface) DeleteAccount(ctx context.Context, userID int, username string, userEmail string) error {
	ret := _mock.Called(ctx, userID, username, userEmail)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, userID, username, userEmail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountDeletionServiceInterface_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAccountDeletionServiceInterface_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - username string
//   - userEmail string
func (_e *MockAccountDeletionServiceInterface_Expecter) DeleteAccount(ctx any, userID any, username any, userEmail any) *MockAccountDeletionServiceInterface_DeleteAccount_Call {
	return &MockAccountDeletionServiceInterface_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, userID, username, userEmail)}
}

func (_c *MockAccountDeletionServiceInterface_DeleteAccount_Call) Run(run func(ctx context.Context, userID int, username string, userEmail string)) *MockAccountDeletionServiceInterface_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountDeletionServiceInterface_DeleteAccount_Call) Return(err error) *MockAccountDeletionServiceInterface_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountDeletionServiceInterface_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context, userID int, username string, userEmail string) error) *MockAccountDeletionServiceInterface_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConfirmationString provides a mock function for the type MockAccountDeletionServiceInterface
func (_mock *MockAccountDeletionServiceInterface) ValidateConfirmationString(confirmation string) error {
	ret := _mock.Called(confirmation)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConfirmationString")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(confirmation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountDeletionServiceInterface_ValidateConfirmationString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConfirmationString'
type MockAccountDeletionServiceInterface_ValidateConfirmationString_Call struct {
	*mock.Call
}

// ValidateConfirmationString is a helper method to define mock.On call
//   - confirmation string
func (_e *MockAccountDeletionServiceInterface_Expecter) ValidateConfirmationString(confirmation any) *MockAccountDeletionServiceInterface_ValidateConfirmationString_Call {
	return &MockAccountDeletionServiceInterface_ValidateConfirmationString_Call{Call: _e.mock.On("ValidateConfirmationString", confirmation)}
}

func (_c *MockAccountDeletionServiceInterface_ValidateConfirmationString_Call) Run(run func(confirmation string)) *MockAccountDeletionServiceInterface_ValidateConfirmationString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountDeletionServiceInterface_ValidateConfirmationString_Call) Return(err error) *MockAccountDeletionServiceInterface_ValidateConfirmationString_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountDeletionServiceInterface_ValidateConfirmationString_Call) RunAndReturn(run func(confirmation string) error) *MockAccountDeletionServiceInterface_ValidateConfirmationString_Call {
	_c.Call.Return(run)
	return _c
}
