// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/user"
	"github.com/aristorinjuang/lesstruct/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileServiceInterface creates a new instance of MockProfileServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileServiceInterface {
	mock := &MockProfileServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileServiceInterface is an autogenerated mock type for the ProfileServiceInterface type
type MockProfileServiceInterface struct {
	mock.Mock
}

type MockProfileServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileServiceInterface) EXPECT() *MockProfileServiceInterface_Expecter {
	return &MockProfileServiceInterface_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockProfileServiceInterface
func (_mock *MockProfileServiceInterface) ChangePassword(ctx context.Context, userID int, currentPassword string, newPassword string) error {
	ret := _mock.Called(ctx, userID, currentPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, userID, currentPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileServiceInterface_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockProfileServiceInterface_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - currentPassword string
//   - newPassword string
func (_e *MockProfileServiceInterface_Expecter) ChangePassword(ctx any, userID any, currentPassword any, newPassword any) *MockProfileServiceInterface_ChangePassword_Call {
	return &MockProfileServiceInterface_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, currentPassword, newPassword)}
}

func (_c *MockProfileServiceInterface_ChangePassword_Call) Run(run func(ctx context.Context, userID int, currentPassword string, newPassword string)) *MockProfileServiceInterface_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProfileServiceInterface_ChangePassword_Call) Return(err error) *MockProfileServiceInterface_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileServiceInterface_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, userID int, currentPassword string, newPassword string) error) *MockProfileServiceInterface_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// ExportUserData provides a mock function for the type MockProfileServiceInterface
func (_mock *MockProfileServiceInterface) ExportUserData(ctx context.Context, userID int) (*repository.UserDataExport, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ExportUserData")
	}

	var r0 *repository.UserDataExport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*repository.UserDataExport, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *repository.UserDataExport); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.UserDataExport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileServiceInterface_ExportUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportUserData'
type MockProfileServiceInterface_ExportUserData_Call struct {
	*mock.Call
}

// ExportUserData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockProfileServiceInterface_Expecter) ExportUserData(ctx any, userID any) *MockProfileServiceInterface_ExportUserData_Call {
	return &MockProfileServiceInterface_ExportUserData_Call{Call: _e.mock.On("ExportUserData", ctx, userID)}
}

func (_c *MockProfileServiceInterface_ExportUserData_Call) Run(run func(ctx context.Context, userID int)) *MockProfileServiceInterface_ExportUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileServiceInterface_ExportUserData_Call) Return(userDataExport *repository.UserDataExport, err error) *MockProfileServiceInterface_ExportUserData_Call {
	_c.Call.Return(userDataExport, err)
	return _c
}

func (_c *MockProfileServiceInterface_ExportUserData_Call) RunAndReturn(run func(ctx context.Context, userID int) (*repository.UserDataExport, error)) *MockProfileServiceInterface_ExportUserData_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function for the type MockProfileServiceInterface
func (_mock *MockProfileServiceInterface) GetProfile(ctx context.Context, userID int) (*user.Profile, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *user.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*user.Profile, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *user.Profile); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileServiceInterface_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockProfileServiceInterface_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockProfileServiceInterface_Expecter) GetProfile(ctx any, userID any) *MockProfileServiceInterface_GetProfile_Call {
	return &MockProfileServiceInterface_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockProfileServiceInterface_GetProfile_Call) Run(run func(ctx context.Context, userID int)) *MockProfileServiceInterface_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileServiceInterface_GetProfile_Call) Return(profile *user.Profile, err error) *MockProfileServiceInterface_GetProfile_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileServiceInterface_GetProfile_Call) RunAndReturn(run func(ctx context.Context, userID int) (*user.Profile, error)) *MockProfileServiceInterface_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCustomFields provides a mock function for the type MockProfileServiceInterface
func (_mock *MockProfileServiceInterface) UpdateCustomFields(ctx context.Context, userID int, customFields map[string]any, isAdmin bool) error {
	ret := _mock.Called(ctx, userID, customFields, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomFields")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, map[string]any, bool) error); ok {
		r0 = returnFunc(ctx, userID, customFields, isAdmin)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileServiceInterface_UpdateCustomFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCustomFields'
type MockProfileServiceInterface_UpdateCustomFields_Call struct {
	*mock.Call
}

// UpdateCustomFields is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - customFields map[string]any
//   - isAdmin bool
func (_e *MockProfileServiceInterface_Expecter) UpdateCustomFields(ctx any, userID any, customFields any, isAdmin any) *MockProfileServiceInterface_UpdateCustomFields_Call {
	return &MockProfileServiceInterface_UpdateCustomFields_Call{Call: _e.mock.On("UpdateCustomFields", ctx, userID, customFields, isAdmin)}
}

func (_c *MockProfileServiceInterface_UpdateCustomFields_Call) Run(run func(ctx context.Context, userID int, customFields map[string]any, isAdmin bool)) *MockProfileServiceInterface_UpdateCustomFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProfileServiceInterface_UpdateCustomFields_Call) Return(err error) *MockProfileServiceInterface_UpdateCustomFields_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileServiceInterface_UpdateCustomFields_Call) RunAndReturn(run func(ctx context.Context, userID int, customFields map[string]any, isAdmin bool) error) *MockProfileServiceInterface_UpdateCustomFields_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmail provides a mock function for the type MockProfileServiceInterface
func (_mock *MockProfileServiceInterface) UpdateEmail(ctx context.Context, userID int, newEmail string, currentPasswordHash string) error {
	ret := _mock.Called(ctx, userID, newEmail, currentPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, userID, newEmail, currentPasswordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileServiceInterface_UpdateEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmail'
type MockProfileServiceInterface_UpdateEmail_Call struct {
	*mock.Call
}

// UpdateEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - newEmail string
//   - currentPasswordHash string
func (_e *MockProfileServiceInterface_Expecter) UpdateEmail(ctx any, userID any, newEmail any, currentPasswordHash any) *MockProfileServiceInterface_UpdateEmail_Call {
	return &MockProfileServiceInterface_UpdateEmail_Call{Call: _e.mock.On("UpdateEmail", ctx, userID, newEmail, currentPasswordHash)}
}

func (_c *MockProfileServiceInterface_UpdateEmail_Call) Run(run func(ctx context.Context, userID int, newEmail string, currentPasswordHash string)) *MockProfileServiceInterface_UpdateEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProfileServiceInterface_UpdateEmail_Call) Return(err error) *MockProfileServiceInterface_UpdateEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileServiceInterface_UpdateEmail_Call) RunAndReturn(run func(ctx context.Context, userID int, newEmail string, currentPasswordHash string) error) *MockProfileServiceInterface_UpdateEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateName provides a mock function for the type MockProfileServiceInterface
func (_mock *MockProfileServiceInterface) UpdateName(ctx context.Context, userID int, name string) error {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileServiceInterface_UpdateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateName'
type MockProfileServiceInterface_UpdateName_Call struct {
	*mock.Call
}

// UpdateName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - name string
func (_e *MockProfileServiceInterface_Expecter) UpdateName(ctx any, userID any, name any) *MockProfileServiceInterface_UpdateName_Call {
	return &MockProfileServiceInterface_UpdateName_Call{Call: _e.mock.On("UpdateName", ctx, userID, name)}
}

func (_c *MockProfileServiceInterface_UpdateName_Call) Run(run func(ctx context.Context, userID int, name string)) *MockProfileServiceInterface_UpdateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileServiceInterface_UpdateName_Call) Return(err error) *MockProfileServiceInterface_UpdateName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileServiceInterface_UpdateName_Call) RunAndReturn(run func(ctx context.Context, userID int, name string) error) *MockProfileServiceInterface_UpdateName_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmailUpdate provides a mock function for the type MockProfileServiceInterface
func (_mock *MockProfileServiceInterface) VerifyEmailUpdate(ctx context.Context, token string) (int, string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmailUpdate")
	}

	var r0 int
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProfileServiceInterface_VerifyEmailUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmailUpdate'
type MockProfileServiceInterface_VerifyEmailUpdate_Call struct {
	*mock.Call
}

// VerifyEmailUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockProfileServiceInterface_Expecter) VerifyEmailUpdate(ctx any, token any) *MockProfileServiceInterface_VerifyEmailUpdate_Call {
	return &MockProfileServiceInterface_VerifyEmailUpdate_Call{Call: _e.mock.On("VerifyEmailUpdate", ctx, token)}
}

func (_c *MockProfileServiceInterface_VerifyEmailUpdate_Call) Run(run func(ctx context.Context, token string)) *MockProfileServiceInterface_VerifyEmailUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileServiceInterface_VerifyEmailUpdate_Call) Return(n int, s string, err error) *MockProfileServiceInterface_VerifyEmailUpdate_Call {
	_c.Call.Return(n, s, err)
	return _c
}

func (_c *MockProfileServiceInterface_VerifyEmailUpdate_Call) RunAndReturn(run func(ctx context.Context, token string) (int, string, error)) *MockProfileServiceInterface_VerifyEmailUpdate_Call {
	_c.Call.Return(run)
	return _c
}
