// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// newMocksystemFieldProvider creates a new instance of mocksystemFieldProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksystemFieldProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksystemFieldProvider {
	mock := &mocksystemFieldProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksystemFieldProvider is an autogenerated mock type for the systemFieldProvider type
type mocksystemFieldProvider struct {
	mock.Mock
}

type mocksystemFieldProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksystemFieldProvider) EXPECT() *mocksystemFieldProvider_Expecter {
	return &mocksystemFieldProvider_Expecter{mock: &_m.Mock}
}

// GetUserSystemFieldSlugs provides a mock function for the type mocksystemFieldProvider
func (_mock *mocksystemFieldProvider) GetUserSystemFieldSlugs() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserSystemFieldSlugs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// mocksystemFieldProvider_GetUserSystemFieldSlugs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSystemFieldSlugs'
type mocksystemFieldProvider_GetUserSystemFieldSlugs_Call struct {
	*mock.Call
}

// GetUserSystemFieldSlugs is a helper method to define mock.On call
func (_e *mocksystemFieldProvider_Expecter) GetUserSystemFieldSlugs() *mocksystemFieldProvider_GetUserSystemFieldSlugs_Call {
	return &mocksystemFieldProvider_GetUserSystemFieldSlugs_Call{Call: _e.mock.On("GetUserSystemFieldSlugs")}
}

func (_c *mocksystemFieldProvider_GetUserSystemFieldSlugs_Call) Run(run func()) *mocksystemFieldProvider_GetUserSystemFieldSlugs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksystemFieldProvider_GetUserSystemFieldSlugs_Call) Return(strings []string) *mocksystemFieldProvider_GetUserSystemFieldSlugs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *mocksystemFieldProvider_GetUserSystemFieldSlugs_Call) RunAndReturn(run func() []string) *mocksystemFieldProvider_GetUserSystemFieldSlugs_Call {
	_c.Call.Return(run)
	return _c
}
