// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// CheckEmailExistsForOtherUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CheckEmailExistsForOtherUser(ctx context.Context, userID int, email string) (bool, error) {
	ret := _mock.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckEmailExistsForOtherUser")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) (bool, error)); ok {
		return returnFunc(ctx, userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) bool); ok {
		r0 = returnFunc(ctx, userID, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, userID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CheckEmailExistsForOtherUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckEmailExistsForOtherUser'
type MockUserRepo_CheckEmailExistsForOtherUser_Call struct {
	*mock.Call
}

// CheckEmailExistsForOtherUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - email string
func (_e *MockUserRepo_Expecter) CheckEmailExistsForOtherUser(ctx any, userID any, email any) *MockUserRepo_CheckEmailExistsForOtherUser_Call {
	return &MockUserRepo_CheckEmailExistsForOtherUser_Call{Call: _e.mock.On("CheckEmailExistsForOtherUser", ctx, userID, email)}
}

func (_c *MockUserRepo_CheckEmailExistsForOtherUser_Call) Run(run func(ctx context.Context, userID int, email string)) *MockUserRepo_CheckEmailExistsForOtherUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_CheckEmailExistsForOtherUser_Call) Return(b bool, err error) *MockUserRepo_CheckEmailExistsForOtherUser_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepo_CheckEmailExistsForOtherUser_Call) RunAndReturn(run func(ctx context.Context, userID int, email string) (bool, error)) *MockUserRepo_CheckEmailExistsForOtherUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) DeleteUser(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserRepo_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) DeleteUser(ctx any, userID any) *MockUserRepo_DeleteUser_Call {
	return &MockUserRepo_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userID)}
}

func (_c *MockUserRepo_DeleteUser_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_DeleteUser_Call) Return(err error) *MockUserRepo_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetAllUsers(ctx context.Context, status string, limit int, offset int) ([]*repository.User, error) {
	ret := _mock.Called(ctx, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*repository.User, error)); ok {
		return returnFunc(ctx, status, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*repository.User); ok {
		r0 = returnFunc(ctx, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserRepo_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - limit int
//   - offset int
func (_e *MockUserRepo_Expecter) GetAllUsers(ctx any, status any, limit any, offset any) *MockUserRepo_GetAllUsers_Call {
	return &MockUserRepo_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx, status, limit, offset)}
}

func (_c *MockUserRepo_GetAllUsers_Call) Run(run func(ctx context.Context, status string, limit int, offset int)) *MockUserRepo_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetAllUsers_Call) Return(users []*repository.User, err error) *MockUserRepo_GetAllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepo_GetAllUsers_Call) RunAndReturn(run func(ctx context.Context, status string, limit int, offset int) ([]*repository.User, error)) *MockUserRepo_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingUsers provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetPendingUsers(ctx context.Context, limit int, offset int) ([]*repository.User, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingUsers")
	}

	var r0 []*repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*repository.User, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*repository.User); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetPendingUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingUsers'
type MockUserRepo_GetPendingUsers_Call struct {
	*mock.Call
}

// GetPendingUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockUserRepo_Expecter) GetPendingUsers(ctx any, limit any, offset any) *MockUserRepo_GetPendingUsers_Call {
	return &MockUserRepo_GetPendingUsers_Call{Call: _e.mock.On("GetPendingUsers", ctx, limit, offset)}
}

func (_c *MockUserRepo_GetPendingUsers_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockUserRepo_GetPendingUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetPendingUsers_Call) Return(users []*repository.User, err error) *MockUserRepo_GetPendingUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepo_GetPendingUsers_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]*repository.User, error)) *MockUserRepo_GetPendingUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByID(ctx context.Context, userID int) (*repository.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *repository.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*repository.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *repository.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepo_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) GetUserByID(ctx any, userID any) *MockUserRepo_GetUserByID_Call {
	return &MockUserRepo_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserRepo_GetUserByID_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) Return(user *repository.User, err error) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID int) (*repository.User, error)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserStatus provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserStatus(ctx context.Context, userID int) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserStatus'
type MockUserRepo_GetUserStatus_Call struct {
	*mock.Call
}

// GetUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) GetUserStatus(ctx any, userID any) *MockUserRepo_GetUserStatus_Call {
	return &MockUserRepo_GetUserStatus_Call{Call: _e.mock.On("GetUserStatus", ctx, userID)}
}

func (_c *MockUserRepo_GetUserStatus_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_GetUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserStatus_Call) Return(s string, err error) *MockUserRepo_GetUserStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserRepo_GetUserStatus_Call) RunAndReturn(run func(ctx context.Context, userID int) (string, error)) *MockUserRepo_GetUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) SoftDeleteUser(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_SoftDeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteUser'
type MockUserRepo_SoftDeleteUser_Call struct {
	*mock.Call
}

// SoftDeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) SoftDeleteUser(ctx any, userID any) *MockUserRepo_SoftDeleteUser_Call {
	return &MockUserRepo_SoftDeleteUser_Call{Call: _e.mock.On("SoftDeleteUser", ctx, userID)}
}

func (_c *MockUserRepo_SoftDeleteUser_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_SoftDeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_SoftDeleteUser_Call) Return(err error) *MockUserRepo_SoftDeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_SoftDeleteUser_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_SoftDeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// SuspendUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) SuspendUser(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SuspendUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_SuspendUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuspendUser'
type MockUserRepo_SuspendUser_Call struct {
	*mock.Call
}

// SuspendUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) SuspendUser(ctx any, userID any) *MockUserRepo_SuspendUser_Call {
	return &MockUserRepo_SuspendUser_Call{Call: _e.mock.On("SuspendUser", ctx, userID)}
}

func (_c *MockUserRepo_SuspendUser_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_SuspendUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_SuspendUser_Call) Return(err error) *MockUserRepo_SuspendUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_SuspendUser_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_SuspendUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnsuspendUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UnsuspendUser(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnsuspendUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UnsuspendUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsuspendUser'
type MockUserRepo_UnsuspendUser_Call struct {
	*mock.Call
}

// UnsuspendUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) UnsuspendUser(ctx any, userID any) *MockUserRepo_UnsuspendUser_Call {
	return &MockUserRepo_UnsuspendUser_Call{Call: _e.mock.On("UnsuspendUser", ctx, userID)}
}

func (_c *MockUserRepo_UnsuspendUser_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_UnsuspendUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_UnsuspendUser_Call) Return(err error) *MockUserRepo_UnsuspendUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UnsuspendUser_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_UnsuspendUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateProfile(ctx context.Context, userID int, name string, email string, role string, customFields map[string]any) error {
	ret := _mock.Called(ctx, userID, name, email, role, customFields)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string, string, map[string]any) error); ok {
		r0 = returnFunc(ctx, userID, name, email, role, customFields)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserRepo_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - name string
//   - email string
//   - role string
//   - customFields map[string]any
func (_e *MockUserRepo_Expecter) UpdateProfile(ctx any, userID any, name any, email any, role any, customFields any) *MockUserRepo_UpdateProfile_Call {
	return &MockUserRepo_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, name, email, role, customFields)}
}

func (_c *MockUserRepo_UpdateProfile_Call) Run(run func(ctx context.Context, userID int, name string, email string, role string, customFields map[string]any)) *MockUserRepo_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 map[string]any
		if args[5] != nil {
			arg5 = args[5].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateProfile_Call) Return(err error) *MockUserRepo_UpdateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, userID int, name string, email string, role string, customFields map[string]any) error) *MockUserRepo_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStatus provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateUserStatus(ctx context.Context, userID int, status string) error {
	ret := _mock.Called(ctx, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStatus'
type MockUserRepo_UpdateUserStatus_Call struct {
	*mock.Call
}

// UpdateUserStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - status string
func (_e *MockUserRepo_Expecter) UpdateUserStatus(ctx any, userID any, status any) *MockUserRepo_UpdateUserStatus_Call {
	return &MockUserRepo_UpdateUserStatus_Call{Call: _e.mock.On("UpdateUserStatus", ctx, userID, status)}
}

func (_c *MockUserRepo_UpdateUserStatus_Call) Run(run func(ctx context.Context, userID int, status string)) *MockUserRepo_UpdateUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateUserStatus_Call) Return(err error) *MockUserRepo_UpdateUserStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateUserStatus_Call) RunAndReturn(run func(ctx context.Context, userID int, status string) error) *MockUserRepo_UpdateUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStatusIfCurrentStatus provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateUserStatusIfCurrentStatus(ctx context.Context, userID int, currentStatus string, newStatus string) error {
	ret := _mock.Called(ctx, userID, currentStatus, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatusIfCurrentStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, userID, currentStatus, newStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateUserStatusIfCurrentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStatusIfCurrentStatus'
type MockUserRepo_UpdateUserStatusIfCurrentStatus_Call struct {
	*mock.Call
}

// UpdateUserStatusIfCurrentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - currentStatus string
//   - newStatus string
func (_e *MockUserRepo_Expecter) UpdateUserStatusIfCurrentStatus(ctx any, userID any, currentStatus any, newStatus any) *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call {
	return &MockUserRepo_UpdateUserStatusIfCurrentStatus_Call{Call: _e.mock.On("UpdateUserStatusIfCurrentStatus", ctx, userID, currentStatus, newStatus)}
}

func (_c *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call) Run(run func(ctx context.Context, userID int, currentStatus string, newStatus string)) *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call) Return(err error) *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call) RunAndReturn(run func(ctx context.Context, userID int, currentStatus string, newStatus string) error) *MockUserRepo_UpdateUserStatusIfCurrentStatus_Call {
	_c.Call.Return(run)
	return _c
}
