// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/content"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContentService creates a new instance of MockContentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentService {
	mock := &MockContentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentService is an autogenerated mock type for the ContentService type
type MockContentService struct {
	mock.Mock
}

type MockContentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentService) EXPECT() *MockContentService_Expecter {
	return &MockContentService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockContentService
func (_mock *MockContentService) Create(ctx context.Context, userID int, req content.CreateContentRequest) (*content.Content, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, content.CreateContentRequest) (*content.Content, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, content.CreateContentRequest) *content.Content); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, content.CreateContentRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockContentService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - req content.CreateContentRequest
func (_e *MockContentService_Expecter) Create(ctx any, userID any, req any) *MockContentService_Create_Call {
	return &MockContentService_Create_Call{Call: _e.mock.On("Create", ctx, userID, req)}
}

func (_c *MockContentService_Create_Call) Run(run func(ctx context.Context, userID int, req content.CreateContentRequest)) *MockContentService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 content.CreateContentRequest
		if args[2] != nil {
			arg2 = args[2].(content.CreateContentRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContentService_Create_Call) Return(content1 *content.Content, err error) *MockContentService_Create_Call {
	_c.Call.Return(content1, err)
	return _c
}

func (_c *MockContentService_Create_Call) RunAndReturn(run func(ctx context.Context, userID int, req content.CreateContentRequest) (*content.Content, error)) *MockContentService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteContent provides a mock function for the type MockContentService
func (_mock *MockContentService) DeleteContent(ctx context.Context, id int, userID int, role string) error {
	ret := _mock.Called(ctx, id, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for DeleteContent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) error); ok {
		r0 = returnFunc(ctx, id, userID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContentService_DeleteContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteContent'
type MockContentService_DeleteContent_Call struct {
	*mock.Call
}

// DeleteContent is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID int
//   - role string
func (_e *MockContentService_Expecter) DeleteContent(ctx any, id any, userID any, role any) *MockContentService_DeleteContent_Call {
	return &MockContentService_DeleteContent_Call{Call: _e.mock.On("DeleteContent", ctx, id, userID, role)}
}

func (_c *MockContentService_DeleteContent_Call) Run(run func(ctx context.Context, id int, userID int, role string)) *MockContentService_DeleteContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContentService_DeleteContent_Call) Return(err error) *MockContentService_DeleteContent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContentService_DeleteContent_Call) RunAndReturn(run func(ctx context.Context, id int, userID int, role string) error) *MockContentService_DeleteContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockContentService
func (_mock *MockContentService) GetByID(ctx context.Context, id int) (*content.Content, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*content.Content, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *content.Content); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockContentService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockContentService_Expecter) GetByID(ctx any, id any) *MockContentService_GetByID_Call {
	return &MockContentService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockContentService_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockContentService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContentService_GetByID_Call) Return(content1 *content.Content, err error) *MockContentService_GetByID_Call {
	_c.Call.Return(content1, err)
	return _c
}

func (_c *MockContentService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*content.Content, error)) *MockContentService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCursor provides a mock function for the type MockContentService
func (_mock *MockContentService) ListByCursor(ctx context.Context, userID int, limit int, beforeID int, filters content.ContentFilters) ([]*content.Content, error) {
	ret := _mock.Called(ctx, userID, limit, beforeID, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListByCursor")
	}

	var r0 []*content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int, content.ContentFilters) ([]*content.Content, error)); ok {
		return returnFunc(ctx, userID, limit, beforeID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int, content.ContentFilters) []*content.Content); ok {
		r0 = returnFunc(ctx, userID, limit, beforeID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, int, content.ContentFilters) error); ok {
		r1 = returnFunc(ctx, userID, limit, beforeID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_ListByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCursor'
type MockContentService_ListByCursor_Call struct {
	*mock.Call
}

// ListByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
//   - beforeID int
//   - filters content.ContentFilters
func (_e *MockContentService_Expecter) ListByCursor(ctx any, userID any, limit any, beforeID any, filters any) *MockContentService_ListByCursor_Call {
	return &MockContentService_ListByCursor_Call{Call: _e.mock.On("ListByCursor", ctx, userID, limit, beforeID, filters)}
}

func (_c *MockContentService_ListByCursor_Call) Run(run func(ctx context.Context, userID int, limit int, beforeID int, filters content.ContentFilters)) *MockContentService_ListByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 content.ContentFilters
		if args[4] != nil {
			arg4 = args[4].(content.ContentFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockContentService_ListByCursor_Call) Return(contents []*content.Content, err error) *MockContentService_ListByCursor_Call {
	_c.Call.Return(contents, err)
	return _c
}

func (_c *MockContentService_ListByCursor_Call) RunAndReturn(run func(ctx context.Context, userID int, limit int, beforeID int, filters content.ContentFilters) ([]*content.Content, error)) *MockContentService_ListByCursor_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockContentService
func (_mock *MockContentService) Publish(ctx context.Context, id int, userID int, role string) (*content.Content, error) {
	ret := _mock.Called(ctx, id, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) (*content.Content, error)); ok {
		return returnFunc(ctx, id, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) *content.Content); ok {
		r0 = returnFunc(ctx, id, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = returnFunc(ctx, id, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockContentService_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID int
//   - role string
func (_e *MockContentService_Expecter) Publish(ctx any, id any, userID any, role any) *MockContentService_Publish_Call {
	return &MockContentService_Publish_Call{Call: _e.mock.On("Publish", ctx, id, userID, role)}
}

func (_c *MockContentService_Publish_Call) Run(run func(ctx context.Context, id int, userID int, role string)) *MockContentService_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContentService_Publish_Call) Return(content1 *content.Content, err error) *MockContentService_Publish_Call {
	_c.Call.Return(content1, err)
	return _c
}

func (_c *MockContentService_Publish_Call) RunAndReturn(run func(ctx context.Context, id int, userID int, role string) (*content.Content, error)) *MockContentService_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// SetSystemFields provides a mock function for the type MockContentService
func (_mock *MockContentService) SetSystemFields(ctx context.Context, contentID int, systemFields map[string]any) (*content.Content, error) {
	ret := _mock.Called(ctx, contentID, systemFields)

	if len(ret) == 0 {
		panic("no return value specified for SetSystemFields")
	}

	var r0 *content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, map[string]any) (*content.Content, error)); ok {
		return returnFunc(ctx, contentID, systemFields)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, map[string]any) *content.Content); ok {
		r0 = returnFunc(ctx, contentID, systemFields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, map[string]any) error); ok {
		r1 = returnFunc(ctx, contentID, systemFields)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_SetSystemFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSystemFields'
type MockContentService_SetSystemFields_Call struct {
	*mock.Call
}

// SetSystemFields is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID int
//   - systemFields map[string]any
func (_e *MockContentService_Expecter) SetSystemFields(ctx any, contentID any, systemFields any) *MockContentService_SetSystemFields_Call {
	return &MockContentService_SetSystemFields_Call{Call: _e.mock.On("SetSystemFields", ctx, contentID, systemFields)}
}

func (_c *MockContentService_SetSystemFields_Call) Run(run func(ctx context.Context, contentID int, systemFields map[string]any)) *MockContentService_SetSystemFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContentService_SetSystemFields_Call) Return(content1 *content.Content, err error) *MockContentService_SetSystemFields_Call {
	_c.Call.Return(content1, err)
	return _c
}

func (_c *MockContentService_SetSystemFields_Call) RunAndReturn(run func(ctx context.Context, contentID int, systemFields map[string]any) (*content.Content, error)) *MockContentService_SetSystemFields_Call {
	_c.Call.Return(run)
	return _c
}

// Unpublish provides a mock function for the type MockContentService
func (_mock *MockContentService) Unpublish(ctx context.Context, id int, userID int, role string) (*content.Content, error) {
	ret := _mock.Called(ctx, id, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for Unpublish")
	}

	var r0 *content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) (*content.Content, error)); ok {
		return returnFunc(ctx, id, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string) *content.Content); ok {
		r0 = returnFunc(ctx, id, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = returnFunc(ctx, id, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_Unpublish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unpublish'
type MockContentService_Unpublish_Call struct {
	*mock.Call
}

// Unpublish is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID int
//   - role string
func (_e *MockContentService_Expecter) Unpublish(ctx any, id any, userID any, role any) *MockContentService_Unpublish_Call {
	return &MockContentService_Unpublish_Call{Call: _e.mock.On("Unpublish", ctx, id, userID, role)}
}

func (_c *MockContentService_Unpublish_Call) Run(run func(ctx context.Context, id int, userID int, role string)) *MockContentService_Unpublish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContentService_Unpublish_Call) Return(content1 *content.Content, err error) *MockContentService_Unpublish_Call {
	_c.Call.Return(content1, err)
	return _c
}

func (_c *MockContentService_Unpublish_Call) RunAndReturn(run func(ctx context.Context, id int, userID int, role string) (*content.Content, error)) *MockContentService_Unpublish_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockContentService
func (_mock *MockContentService) Update(ctx context.Context, id int, userID int, role string, req content.UpdateContentRequest) (*content.Content, error) {
	ret := _mock.Called(ctx, id, userID, role, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, content.UpdateContentRequest) (*content.Content, error)); ok {
		return returnFunc(ctx, id, userID, role, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, content.UpdateContentRequest) *content.Content); ok {
		r0 = returnFunc(ctx, id, userID, role, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, string, content.UpdateContentRequest) error); ok {
		r1 = returnFunc(ctx, id, userID, role, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockContentService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID int
//   - role string
//   - req content.UpdateContentRequest
func (_e *MockContentService_Expecter) Update(ctx any, id any, userID any, role any, req any) *MockContentService_Update_Call {
	return &MockContentService_Update_Call{Call: _e.mock.On("Update", ctx, id, userID, role, req)}
}

func (_c *MockContentService_Update_Call) Run(run func(ctx context.Context, id int, userID int, role string, req content.UpdateContentRequest)) *MockContentService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 content.UpdateContentRequest
		if args[4] != nil {
			arg4 = args[4].(content.UpdateContentRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockContentService_Update_Call) Return(content1 *content.Content, err error) *MockContentService_Update_Call {
	_c.Call.Return(content1, err)
	return _c
}

func (_c *MockContentService_Update_Call) RunAndReturn(run func(ctx context.Context, id int, userID int, role string, req content.UpdateContentRequest) (*content.Content, error)) *MockContentService_Update_Call {
	_c.Call.Return(run)
	return _c
}
