// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/media"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMediaService creates a new instance of MockMediaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaService {
	mock := &MockMediaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMediaService is an autogenerated mock type for the MediaService type
type MockMediaService struct {
	mock.Mock
}

type MockMediaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaService) EXPECT() *MockMediaService_Expecter {
	return &MockMediaService_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockMediaService
func (_mock *MockMediaService) GetByID(ctx context.Context, id int) (*media.Media, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*media.Media, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *media.Media); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMediaService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockMediaService_Expecter) GetByID(ctx any, id any) *MockMediaService_GetByID_Call {
	return &MockMediaService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockMediaService_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockMediaService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaService_GetByID_Call) Return(media1 *media.Media, err error) *MockMediaService_GetByID_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *MockMediaService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*media.Media, error)) *MockMediaService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCursor provides a mock function for the type MockMediaService
func (_mock *MockMediaService) ListByCursor(ctx context.Context, userID int, limit int, beforeID int) ([]*media.Media, error) {
	ret := _mock.Called(ctx, userID, limit, beforeID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCursor")
	}

	var r0 []*media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*media.Media, error)); ok {
		return returnFunc(ctx, userID, limit, beforeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) []*media.Media); ok {
		r0 = returnFunc(ctx, userID, limit, beforeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, beforeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaService_ListByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCursor'
type MockMediaService_ListByCursor_Call struct {
	*mock.Call
}

// ListByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
//   - beforeID int
func (_e *MockMediaService_Expecter) ListByCursor(ctx any, userID any, limit any, beforeID any) *MockMediaService_ListByCursor_Call {
	return &MockMediaService_ListByCursor_Call{Call: _e.mock.On("ListByCursor", ctx, userID, limit, beforeID)}
}

func (_c *MockMediaService_ListByCursor_Call) Run(run func(ctx context.Context, userID int, limit int, beforeID int)) *MockMediaService_ListByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMediaService_ListByCursor_Call) Return(medias []*media.Media, err error) *MockMediaService_ListByCursor_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockMediaService_ListByCursor_Call) RunAndReturn(run func(ctx context.Context, userID int, limit int, beforeID int) ([]*media.Media, error)) *MockMediaService_ListByCursor_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockMediaService
func (_mock *MockMediaService) Upload(ctx context.Context, req media.UploadRequest) (*media.Media, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, media.UploadRequest) (*media.Media, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, media.UploadRequest) *media.Media); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, media.UploadRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockMediaService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - req media.UploadRequest
func (_e *MockMediaService_Expecter) Upload(ctx any, req any) *MockMediaService_Upload_Call {
	return &MockMediaService_Upload_Call{Call: _e.mock.On("Upload", ctx, req)}
}

func (_c *MockMediaService_Upload_Call) Run(run func(ctx context.Context, req media.UploadRequest)) *MockMediaService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 media.UploadRequest
		if args[1] != nil {
			arg1 = args[1].(media.UploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaService_Upload_Call) Return(media1 *media.Media, err error) *MockMediaService_Upload_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *MockMediaService_Upload_Call) RunAndReturn(run func(ctx context.Context, req media.UploadRequest) (*media.Media, error)) *MockMediaService_Upload_Call {
	_c.Call.Return(run)
	return _c
}
