// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublicFieldLookup creates a new instance of MockPublicFieldLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublicFieldLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublicFieldLookup {
	mock := &MockPublicFieldLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublicFieldLookup is an autogenerated mock type for the PublicFieldLookup type
type MockPublicFieldLookup struct {
	mock.Mock
}

type MockPublicFieldLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublicFieldLookup) EXPECT() *MockPublicFieldLookup_Expecter {
	return &MockPublicFieldLookup_Expecter{mock: &_m.Mock}
}

// ExposedFields provides a mock function for the type MockPublicFieldLookup
func (_mock *MockPublicFieldLookup) ExposedFields(resource string, postType string) []string {
	ret := _mock.Called(resource, postType)

	if len(ret) == 0 {
		panic("no return value specified for ExposedFields")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = returnFunc(resource, postType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockPublicFieldLookup_ExposedFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExposedFields'
type MockPublicFieldLookup_ExposedFields_Call struct {
	*mock.Call
}

// ExposedFields is a helper method to define mock.On call
//   - resource string
//   - postType string
func (_e *MockPublicFieldLookup_Expecter) ExposedFields(resource any, postType any) *MockPublicFieldLookup_ExposedFields_Call {
	return &MockPublicFieldLookup_ExposedFields_Call{Call: _e.mock.On("ExposedFields", resource, postType)}
}

func (_c *MockPublicFieldLookup_ExposedFields_Call) Run(run func(resource string, postType string)) *MockPublicFieldLookup_ExposedFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublicFieldLookup_ExposedFields_Call) Return(strings []string) *MockPublicFieldLookup_ExposedFields_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockPublicFieldLookup_ExposedFields_Call) RunAndReturn(run func(resource string, postType string) []string) *MockPublicFieldLookup_ExposedFields_Call {
	_c.Call.Return(run)
	return _c
}
