// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/aristorinjuang/lesstruct/internal/domain/customfield"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserFieldResolver creates a new instance of MockUserFieldResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserFieldResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserFieldResolver {
	mock := &MockUserFieldResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserFieldResolver is an autogenerated mock type for the UserFieldResolver type
type MockUserFieldResolver struct {
	mock.Mock
}

type MockUserFieldResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserFieldResolver) EXPECT() *MockUserFieldResolver_Expecter {
	return &MockUserFieldResolver_Expecter{mock: &_m.Mock}
}

// GetUserFields provides a mock function for the type MockUserFieldResolver
func (_mock *MockUserFieldResolver) GetUserFields() []customfield.FieldSchema {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserFields")
	}

	var r0 []customfield.FieldSchema
	if returnFunc, ok := ret.Get(0).(func() []customfield.FieldSchema); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customfield.FieldSchema)
		}
	}
	return r0
}

// MockUserFieldResolver_GetUserFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFields'
type MockUserFieldResolver_GetUserFields_Call struct {
	*mock.Call
}

// GetUserFields is a helper method to define mock.On call
func (_e *MockUserFieldResolver_Expecter) GetUserFields() *MockUserFieldResolver_GetUserFields_Call {
	return &MockUserFieldResolver_GetUserFields_Call{Call: _e.mock.On("GetUserFields")}
}

func (_c *MockUserFieldResolver_GetUserFields_Call) Run(run func()) *MockUserFieldResolver_GetUserFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserFieldResolver_GetUserFields_Call) Return(fieldSchemas []customfield.FieldSchema) *MockUserFieldResolver_GetUserFields_Call {
	_c.Call.Return(fieldSchemas)
	return _c
}

func (_c *MockUserFieldResolver_GetUserFields_Call) RunAndReturn(run func() []customfield.FieldSchema) *MockUserFieldResolver_GetUserFields_Call {
	_c.Call.Return(run)
	return _c
}
