// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/api/contentpage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// GetUserByUsername provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) GetUserByUsername(ctx context.Context, username string) (*contentpage.UserBasicInfo, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *contentpage.UserBasicInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*contentpage.UserBasicInfo, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *contentpage.UserBasicInfo); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contentpage.UserBasicInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUserProvider_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserProvider_Expecter) GetUserByUsername(ctx any, username any) *MockUserProvider_GetUserByUsername_Call {
	return &MockUserProvider_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUserProvider_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserProvider_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_GetUserByUsername_Call) Return(userBasicInfo *contentpage.UserBasicInfo, err error) *MockUserProvider_GetUserByUsername_Call {
	_c.Call.Return(userBasicInfo, err)
	return _c
}

func (_c *MockUserProvider_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*contentpage.UserBasicInfo, error)) *MockUserProvider_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}
