// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

type MockEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailService) EXPECT() *MockEmailService_Expecter {
	return &MockEmailService_Expecter{mock: &_m.Mock}
}

// SendAccountCreatedEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendAccountCreatedEmail(ctx context.Context, to string, username string, plainPassword string) error {
	ret := _mock.Called(ctx, to, username, plainPassword)

	if len(ret) == 0 {
		panic("no return value specified for SendAccountCreatedEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, username, plainPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendAccountCreatedEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAccountCreatedEmail'
type MockEmailService_SendAccountCreatedEmail_Call struct {
	*mock.Call
}

// SendAccountCreatedEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
//   - plainPassword string
func (_e *MockEmailService_Expecter) SendAccountCreatedEmail(ctx any, to any, username any, plainPassword any) *MockEmailService_SendAccountCreatedEmail_Call {
	return &MockEmailService_SendAccountCreatedEmail_Call{Call: _e.mock.On("SendAccountCreatedEmail", ctx, to, username, plainPassword)}
}

func (_c *MockEmailService_SendAccountCreatedEmail_Call) Run(run func(ctx context.Context, to string, username string, plainPassword string)) *MockEmailService_SendAccountCreatedEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailService_SendAccountCreatedEmail_Call) Return(err error) *MockEmailService_SendAccountCreatedEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendAccountCreatedEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string, plainPassword string) error) *MockEmailService_SendAccountCreatedEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendAccountDeletedNotification provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendAccountDeletedNotification(ctx context.Context, to string, username string) error {
	ret := _mock.Called(ctx, to, username)

	if len(ret) == 0 {
		panic("no return value specified for SendAccountDeletedNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, to, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendAccountDeletedNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAccountDeletedNotification'
type MockEmailService_SendAccountDeletedNotification_Call struct {
	*mock.Call
}

// SendAccountDeletedNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
func (_e *MockEmailService_Expecter) SendAccountDeletedNotification(ctx any, to any, username any) *MockEmailService_SendAccountDeletedNotification_Call {
	return &MockEmailService_SendAccountDeletedNotification_Call{Call: _e.mock.On("SendAccountDeletedNotification", ctx, to, username)}
}

func (_c *MockEmailService_SendAccountDeletedNotification_Call) Run(run func(ctx context.Context, to string, username string)) *MockEmailService_SendAccountDeletedNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailService_SendAccountDeletedNotification_Call) Return(err error) *MockEmailService_SendAccountDeletedNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendAccountDeletedNotification_Call) RunAndReturn(run func(ctx context.Context, to string, username string) error) *MockEmailService_SendAccountDeletedNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendAccountLockoutEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendAccountLockoutEmail(ctx context.Context, to string, username string) error {
	ret := _mock.Called(ctx, to, username)

	if len(ret) == 0 {
		panic("no return value specified for SendAccountLockoutEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, to, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendAccountLockoutEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAccountLockoutEmail'
type MockEmailService_SendAccountLockoutEmail_Call struct {
	*mock.Call
}

// SendAccountLockoutEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
func (_e *MockEmailService_Expecter) SendAccountLockoutEmail(ctx any, to any, username any) *MockEmailService_SendAccountLockoutEmail_Call {
	return &MockEmailService_SendAccountLockoutEmail_Call{Call: _e.mock.On("SendAccountLockoutEmail", ctx, to, username)}
}

func (_c *MockEmailService_SendAccountLockoutEmail_Call) Run(run func(ctx context.Context, to string, username string)) *MockEmailService_SendAccountLockoutEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailService_SendAccountLockoutEmail_Call) Return(err error) *MockEmailService_SendAccountLockoutEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendAccountLockoutEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string) error) *MockEmailService_SendAccountLockoutEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendDataExportNotificationEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendDataExportNotificationEmail(ctx context.Context, to string, username string) error {
	ret := _mock.Called(ctx, to, username)

	if len(ret) == 0 {
		panic("no return value specified for SendDataExportNotificationEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, to, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendDataExportNotificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDataExportNotificationEmail'
type MockEmailService_SendDataExportNotificationEmail_Call struct {
	*mock.Call
}

// SendDataExportNotificationEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
func (_e *MockEmailService_Expecter) SendDataExportNotificationEmail(ctx any, to any, username any) *MockEmailService_SendDataExportNotificationEmail_Call {
	return &MockEmailService_SendDataExportNotificationEmail_Call{Call: _e.mock.On("SendDataExportNotificationEmail", ctx, to, username)}
}

func (_c *MockEmailService_SendDataExportNotificationEmail_Call) Run(run func(ctx context.Context, to string, username string)) *MockEmailService_SendDataExportNotificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailService_SendDataExportNotificationEmail_Call) Return(err error) *MockEmailService_SendDataExportNotificationEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendDataExportNotificationEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string) error) *MockEmailService_SendDataExportNotificationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendEmailUpdateVerificationEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendEmailUpdateVerificationEmail(ctx context.Context, to string, username string, token string) error {
	ret := _mock.Called(ctx, to, username, token)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailUpdateVerificationEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, username, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendEmailUpdateVerificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailUpdateVerificationEmail'
type MockEmailService_SendEmailUpdateVerificationEmail_Call struct {
	*mock.Call
}

// SendEmailUpdateVerificationEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
//   - token string
func (_e *MockEmailService_Expecter) SendEmailUpdateVerificationEmail(ctx any, to any, username any, token any) *MockEmailService_SendEmailUpdateVerificationEmail_Call {
	return &MockEmailService_SendEmailUpdateVerificationEmail_Call{Call: _e.mock.On("SendEmailUpdateVerificationEmail", ctx, to, username, token)}
}

func (_c *MockEmailService_SendEmailUpdateVerificationEmail_Call) Run(run func(ctx context.Context, to string, username string, token string)) *MockEmailService_SendEmailUpdateVerificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailService_SendEmailUpdateVerificationEmail_Call) Return(err error) *MockEmailService_SendEmailUpdateVerificationEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendEmailUpdateVerificationEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string, token string) error) *MockEmailService_SendEmailUpdateVerificationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendPasswordResetEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendPasswordResetEmail(ctx context.Context, to string, username string, token string) error {
	ret := _mock.Called(ctx, to, username, token)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordResetEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, username, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendPasswordResetEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordResetEmail'
type MockEmailService_SendPasswordResetEmail_Call struct {
	*mock.Call
}

// SendPasswordResetEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
//   - token string
func (_e *MockEmailService_Expecter) SendPasswordResetEmail(ctx any, to any, username any, token any) *MockEmailService_SendPasswordResetEmail_Call {
	return &MockEmailService_SendPasswordResetEmail_Call{Call: _e.mock.On("SendPasswordResetEmail", ctx, to, username, token)}
}

func (_c *MockEmailService_SendPasswordResetEmail_Call) Run(run func(ctx context.Context, to string, username string, token string)) *MockEmailService_SendPasswordResetEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailService_SendPasswordResetEmail_Call) Return(err error) *MockEmailService_SendPasswordResetEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendPasswordResetEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string, token string) error) *MockEmailService_SendPasswordResetEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendUserApprovedEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendUserApprovedEmail(ctx context.Context, to string, username string) error {
	ret := _mock.Called(ctx, to, username)

	if len(ret) == 0 {
		panic("no return value specified for SendUserApprovedEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, to, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendUserApprovedEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUserApprovedEmail'
type MockEmailService_SendUserApprovedEmail_Call struct {
	*mock.Call
}

// SendUserApprovedEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
func (_e *MockEmailService_Expecter) SendUserApprovedEmail(ctx any, to any, username any) *MockEmailService_SendUserApprovedEmail_Call {
	return &MockEmailService_SendUserApprovedEmail_Call{Call: _e.mock.On("SendUserApprovedEmail", ctx, to, username)}
}

func (_c *MockEmailService_SendUserApprovedEmail_Call) Run(run func(ctx context.Context, to string, username string)) *MockEmailService_SendUserApprovedEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailService_SendUserApprovedEmail_Call) Return(err error) *MockEmailService_SendUserApprovedEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendUserApprovedEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string) error) *MockEmailService_SendUserApprovedEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendUserRejectedEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendUserRejectedEmail(ctx context.Context, to string, username string) error {
	ret := _mock.Called(ctx, to, username)

	if len(ret) == 0 {
		panic("no return value specified for SendUserRejectedEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, to, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendUserRejectedEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUserRejectedEmail'
type MockEmailService_SendUserRejectedEmail_Call struct {
	*mock.Call
}

// SendUserRejectedEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
func (_e *MockEmailService_Expecter) SendUserRejectedEmail(ctx any, to any, username any) *MockEmailService_SendUserRejectedEmail_Call {
	return &MockEmailService_SendUserRejectedEmail_Call{Call: _e.mock.On("SendUserRejectedEmail", ctx, to, username)}
}

func (_c *MockEmailService_SendUserRejectedEmail_Call) Run(run func(ctx context.Context, to string, username string)) *MockEmailService_SendUserRejectedEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailService_SendUserRejectedEmail_Call) Return(err error) *MockEmailService_SendUserRejectedEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendUserRejectedEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string) error) *MockEmailService_SendUserRejectedEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendUserSoftDeletedEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendUserSoftDeletedEmail(ctx context.Context, to string, username string, reason string) error {
	ret := _mock.Called(ctx, to, username, reason)

	if len(ret) == 0 {
		panic("no return value specified for SendUserSoftDeletedEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, username, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendUserSoftDeletedEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUserSoftDeletedEmail'
type MockEmailService_SendUserSoftDeletedEmail_Call struct {
	*mock.Call
}

// SendUserSoftDeletedEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
//   - reason string
func (_e *MockEmailService_Expecter) SendUserSoftDeletedEmail(ctx any, to any, username any, reason any) *MockEmailService_SendUserSoftDeletedEmail_Call {
	return &MockEmailService_SendUserSoftDeletedEmail_Call{Call: _e.mock.On("SendUserSoftDeletedEmail", ctx, to, username, reason)}
}

func (_c *MockEmailService_SendUserSoftDeletedEmail_Call) Run(run func(ctx context.Context, to string, username string, reason string)) *MockEmailService_SendUserSoftDeletedEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailService_SendUserSoftDeletedEmail_Call) Return(err error) *MockEmailService_SendUserSoftDeletedEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendUserSoftDeletedEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string, reason string) error) *MockEmailService_SendUserSoftDeletedEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendUserSuspendedEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendUserSuspendedEmail(ctx context.Context, to string, username string, reason string) error {
	ret := _mock.Called(ctx, to, username, reason)

	if len(ret) == 0 {
		panic("no return value specified for SendUserSuspendedEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, username, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendUserSuspendedEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUserSuspendedEmail'
type MockEmailService_SendUserSuspendedEmail_Call struct {
	*mock.Call
}

// SendUserSuspendedEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
//   - reason string
func (_e *MockEmailService_Expecter) SendUserSuspendedEmail(ctx any, to any, username any, reason any) *MockEmailService_SendUserSuspendedEmail_Call {
	return &MockEmailService_SendUserSuspendedEmail_Call{Call: _e.mock.On("SendUserSuspendedEmail", ctx, to, username, reason)}
}

func (_c *MockEmailService_SendUserSuspendedEmail_Call) Run(run func(ctx context.Context, to string, username string, reason string)) *MockEmailService_SendUserSuspendedEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailService_SendUserSuspendedEmail_Call) Return(err error) *MockEmailService_SendUserSuspendedEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendUserSuspendedEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string, reason string) error) *MockEmailService_SendUserSuspendedEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendUserUnsuspendedEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendUserUnsuspendedEmail(ctx context.Context, to string, username string) error {
	ret := _mock.Called(ctx, to, username)

	if len(ret) == 0 {
		panic("no return value specified for SendUserUnsuspendedEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, to, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendUserUnsuspendedEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUserUnsuspendedEmail'
type MockEmailService_SendUserUnsuspendedEmail_Call struct {
	*mock.Call
}

// SendUserUnsuspendedEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
func (_e *MockEmailService_Expecter) SendUserUnsuspendedEmail(ctx any, to any, username any) *MockEmailService_SendUserUnsuspendedEmail_Call {
	return &MockEmailService_SendUserUnsuspendedEmail_Call{Call: _e.mock.On("SendUserUnsuspendedEmail", ctx, to, username)}
}

func (_c *MockEmailService_SendUserUnsuspendedEmail_Call) Run(run func(ctx context.Context, to string, username string)) *MockEmailService_SendUserUnsuspendedEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmailService_SendUserUnsuspendedEmail_Call) Return(err error) *MockEmailService_SendUserUnsuspendedEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendUserUnsuspendedEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string) error) *MockEmailService_SendUserUnsuspendedEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendVerificationEmail provides a mock function for the type MockEmailService
func (_mock *MockEmailService) SendVerificationEmail(ctx context.Context, to string, username string, token string) error {
	ret := _mock.Called(ctx, to, username, token)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, username, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailService_SendVerificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerificationEmail'
type MockEmailService_SendVerificationEmail_Call struct {
	*mock.Call
}

// SendVerificationEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - username string
//   - token string
func (_e *MockEmailService_Expecter) SendVerificationEmail(ctx any, to any, username any, token any) *MockEmailService_SendVerificationEmail_Call {
	return &MockEmailService_SendVerificationEmail_Call{Call: _e.mock.On("SendVerificationEmail", ctx, to, username, token)}
}

func (_c *MockEmailService_SendVerificationEmail_Call) Run(run func(ctx context.Context, to string, username string, token string)) *MockEmailService_SendVerificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailService_SendVerificationEmail_Call) Return(err error) *MockEmailService_SendVerificationEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailService_SendVerificationEmail_Call) RunAndReturn(run func(ctx context.Context, to string, username string, token string) error) *MockEmailService_SendVerificationEmail_Call {
	_c.Call.Return(run)
	return _c
}
