// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockImageGenerationService creates a new instance of MockImageGenerationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageGenerationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageGenerationService {
	mock := &MockImageGenerationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageGenerationService is an autogenerated mock type for the ImageGenerationService type
type MockImageGenerationService struct {
	mock.Mock
}

type MockImageGenerationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageGenerationService) EXPECT() *MockImageGenerationService_Expecter {
	return &MockImageGenerationService_Expecter{mock: &_m.Mock}
}

// GenerateImage provides a mock function for the type MockImageGenerationService
func (_mock *MockImageGenerationService) GenerateImage(ctx context.Context, prompt string) ([]byte, error) {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for GenerateImage")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageGenerationService_GenerateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateImage'
type MockImageGenerationService_GenerateImage_Call struct {
	*mock.Call
}

// GenerateImage is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockImageGenerationService_Expecter) GenerateImage(ctx any, prompt any) *MockImageGenerationService_GenerateImage_Call {
	return &MockImageGenerationService_GenerateImage_Call{Call: _e.mock.On("GenerateImage", ctx, prompt)}
}

func (_c *MockImageGenerationService_GenerateImage_Call) Run(run func(ctx context.Context, prompt string)) *MockImageGenerationService_GenerateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageGenerationService_GenerateImage_Call) Return(bytes []byte, err error) *MockImageGenerationService_GenerateImage_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockImageGenerationService_GenerateImage_Call) RunAndReturn(run func(ctx context.Context, prompt string) ([]byte, error)) *MockImageGenerationService_GenerateImage_Call {
	_c.Call.Return(run)
	return _c
}
