// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/aristorinjuang/lesstruct/internal/domain/media"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockRepository
func (_mock *MockRepository) Count(ctx context.Context, search string, since time.Time) (int, error) {
	ret := _mock.Called(ctx, search, since)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (int, error)); ok {
		return returnFunc(ctx, search, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) int); ok {
		r0 = returnFunc(ctx, search, since)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, search, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - since time.Time
func (_e *MockRepository_Expecter) Count(ctx any, search any, since any) *MockRepository_Count_Call {
	return &MockRepository_Count_Call{Call: _e.mock.On("Count", ctx, search, since)}
}

func (_c *MockRepository_Count_Call) Run(run func(ctx context.Context, search string, since time.Time)) *MockRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Count_Call) Return(n int, err error) *MockRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_Count_Call) RunAndReturn(run func(ctx context.Context, search string, since time.Time) (int, error)) *MockRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, media1 *media.Media) error {
	ret := _mock.Called(ctx, media1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *media.Media) error); ok {
		r0 = returnFunc(ctx, media1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - media1 *media.Media
func (_e *MockRepository_Expecter) Create(ctx any, media1 any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, media1)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, media1 *media.Media)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *media.Media
		if args[1] != nil {
			arg1 = args[1].(*media.Media)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, media1 *media.Media) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteByID(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) DeleteByID(ctx any, id any) *MockRepository_DeleteByID_Call {
	return &MockRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockRepository_DeleteByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteByID_Call) Return(err error) *MockRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByOwner provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteByOwner(ctx context.Context, id int, userID int) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByOwner")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByOwner'
type MockRepository_DeleteByOwner_Call struct {
	*mock.Call
}

// DeleteByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID int
func (_e *MockRepository_Expecter) DeleteByOwner(ctx any, id any, userID any) *MockRepository_DeleteByOwner_Call {
	return &MockRepository_DeleteByOwner_Call{Call: _e.mock.On("DeleteByOwner", ctx, id, userID)}
}

func (_c *MockRepository_DeleteByOwner_Call) Run(run func(ctx context.Context, id int, userID int)) *MockRepository_DeleteByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteByOwner_Call) Return(err error) *MockRepository_DeleteByOwner_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteByOwner_Call) RunAndReturn(run func(ctx context.Context, id int, userID int) error) *MockRepository_DeleteByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByCursor provides a mock function for the type MockRepository
func (_mock *MockRepository) FindAllByCursor(ctx context.Context, limit int, beforeID int) ([]*media.Media, error) {
	ret := _mock.Called(ctx, limit, beforeID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByCursor")
	}

	var r0 []*media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*media.Media, error)); ok {
		return returnFunc(ctx, limit, beforeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*media.Media); ok {
		r0 = returnFunc(ctx, limit, beforeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, beforeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindAllByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByCursor'
type MockRepository_FindAllByCursor_Call struct {
	*mock.Call
}

// FindAllByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - beforeID int
func (_e *MockRepository_Expecter) FindAllByCursor(ctx any, limit any, beforeID any) *MockRepository_FindAllByCursor_Call {
	return &MockRepository_FindAllByCursor_Call{Call: _e.mock.On("FindAllByCursor", ctx, limit, beforeID)}
}

func (_c *MockRepository_FindAllByCursor_Call) Run(run func(ctx context.Context, limit int, beforeID int)) *MockRepository_FindAllByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_FindAllByCursor_Call) Return(medias []*media.Media, err error) *MockRepository_FindAllByCursor_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockRepository_FindAllByCursor_Call) RunAndReturn(run func(ctx context.Context, limit int, beforeID int) ([]*media.Media, error)) *MockRepository_FindAllByCursor_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByDateRangeByCursor provides a mock function for the type MockRepository
func (_mock *MockRepository) FindAllByDateRangeByCursor(ctx context.Context, since time.Time, limit int, beforeID int) ([]*media.Media, error) {
	ret := _mock.Called(ctx, since, limit, beforeID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByDateRangeByCursor")
	}

	var r0 []*media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int, int) ([]*media.Media, error)); ok {
		return returnFunc(ctx, since, limit, beforeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int, int) []*media.Media); ok {
		r0 = returnFunc(ctx, since, limit, beforeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, since, limit, beforeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindAllByDateRangeByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByDateRangeByCursor'
type MockRepository_FindAllByDateRangeByCursor_Call struct {
	*mock.Call
}

// FindAllByDateRangeByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
//   - limit int
//   - beforeID int
func (_e *MockRepository_Expecter) FindAllByDateRangeByCursor(ctx any, since any, limit any, beforeID any) *MockRepository_FindAllByDateRangeByCursor_Call {
	return &MockRepository_FindAllByDateRangeByCursor_Call{Call: _e.mock.On("FindAllByDateRangeByCursor", ctx, since, limit, beforeID)}
}

func (_c *MockRepository_FindAllByDateRangeByCursor_Call) Run(run func(ctx context.Context, since time.Time, limit int, beforeID int)) *MockRepository_FindAllByDateRangeByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_FindAllByDateRangeByCursor_Call) Return(medias []*media.Media, err error) *MockRepository_FindAllByDateRangeByCursor_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockRepository_FindAllByDateRangeByCursor_Call) RunAndReturn(run func(ctx context.Context, since time.Time, limit int, beforeID int) ([]*media.Media, error)) *MockRepository_FindAllByDateRangeByCursor_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByFilenameAndDateRangeByCursor provides a mock function for the type MockRepository
func (_mock *MockRepository) FindAllByFilenameAndDateRangeByCursor(ctx context.Context, filename string, since time.Time, limit int, beforeID int) ([]*media.Media, error) {
	ret := _mock.Called(ctx, filename, since, limit, beforeID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByFilenameAndDateRangeByCursor")
	}

	var r0 []*media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int, int) ([]*media.Media, error)); ok {
		return returnFunc(ctx, filename, since, limit, beforeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int, int) []*media.Media); ok {
		r0 = returnFunc(ctx, filename, since, limit, beforeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, filename, since, limit, beforeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindAllByFilenameAndDateRangeByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByFilenameAndDateRangeByCursor'
type MockRepository_FindAllByFilenameAndDateRangeByCursor_Call struct {
	*mock.Call
}

// FindAllByFilenameAndDateRangeByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
//   - since time.Time
//   - limit int
//   - beforeID int
func (_e *MockRepository_Expecter) FindAllByFilenameAndDateRangeByCursor(ctx any, filename any, since any, limit any, beforeID any) *MockRepository_FindAllByFilenameAndDateRangeByCursor_Call {
	return &MockRepository_FindAllByFilenameAndDateRangeByCursor_Call{Call: _e.mock.On("FindAllByFilenameAndDateRangeByCursor", ctx, filename, since, limit, beforeID)}
}

func (_c *MockRepository_FindAllByFilenameAndDateRangeByCursor_Call) Run(run func(ctx context.Context, filename string, since time.Time, limit int, beforeID int)) *MockRepository_FindAllByFilenameAndDateRangeByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_FindAllByFilenameAndDateRangeByCursor_Call) Return(medias []*media.Media, err error) *MockRepository_FindAllByFilenameAndDateRangeByCursor_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockRepository_FindAllByFilenameAndDateRangeByCursor_Call) RunAndReturn(run func(ctx context.Context, filename string, since time.Time, limit int, beforeID int) ([]*media.Media, error)) *MockRepository_FindAllByFilenameAndDateRangeByCursor_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByFilenameByCursor provides a mock function for the type MockRepository
func (_mock *MockRepository) FindAllByFilenameByCursor(ctx context.Context, filename string, limit int, beforeID int) ([]*media.Media, error) {
	ret := _mock.Called(ctx, filename, limit, beforeID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByFilenameByCursor")
	}

	var r0 []*media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*media.Media, error)); ok {
		return returnFunc(ctx, filename, limit, beforeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*media.Media); ok {
		r0 = returnFunc(ctx, filename, limit, beforeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, filename, limit, beforeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindAllByFilenameByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByFilenameByCursor'
type MockRepository_FindAllByFilenameByCursor_Call struct {
	*mock.Call
}

// FindAllByFilenameByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
//   - limit int
//   - beforeID int
func (_e *MockRepository_Expecter) FindAllByFilenameByCursor(ctx any, filename any, limit any, beforeID any) *MockRepository_FindAllByFilenameByCursor_Call {
	return &MockRepository_FindAllByFilenameByCursor_Call{Call: _e.mock.On("FindAllByFilenameByCursor", ctx, filename, limit, beforeID)}
}

func (_c *MockRepository_FindAllByFilenameByCursor_Call) Run(run func(ctx context.Context, filename string, limit int, beforeID int)) *MockRepository_FindAllByFilenameByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_FindAllByFilenameByCursor_Call) Return(medias []*media.Media, err error) *MockRepository_FindAllByFilenameByCursor_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockRepository_FindAllByFilenameByCursor_Call) RunAndReturn(run func(ctx context.Context, filename string, limit int, beforeID int) ([]*media.Media, error)) *MockRepository_FindAllByFilenameByCursor_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHash provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByHash(ctx context.Context, hash string) (*media.Media, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for FindByHash")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*media.Media, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *media.Media); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHash'
type MockRepository_FindByHash_Call struct {
	*mock.Call
}

// FindByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockRepository_Expecter) FindByHash(ctx any, hash any) *MockRepository_FindByHash_Call {
	return &MockRepository_FindByHash_Call{Call: _e.mock.On("FindByHash", ctx, hash)}
}

func (_c *MockRepository_FindByHash_Call) Run(run func(ctx context.Context, hash string)) *MockRepository_FindByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByHash_Call) Return(media1 *media.Media, err error) *MockRepository_FindByHash_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *MockRepository_FindByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*media.Media, error)) *MockRepository_FindByHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHashPrefix provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByHashPrefix(ctx context.Context, prefix string) (*media.Media, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for FindByHashPrefix")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*media.Media, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *media.Media); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByHashPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHashPrefix'
type MockRepository_FindByHashPrefix_Call struct {
	*mock.Call
}

// FindByHashPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockRepository_Expecter) FindByHashPrefix(ctx any, prefix any) *MockRepository_FindByHashPrefix_Call {
	return &MockRepository_FindByHashPrefix_Call{Call: _e.mock.On("FindByHashPrefix", ctx, prefix)}
}

func (_c *MockRepository_FindByHashPrefix_Call) Run(run func(ctx context.Context, prefix string)) *MockRepository_FindByHashPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByHashPrefix_Call) Return(media1 *media.Media, err error) *MockRepository_FindByHashPrefix_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *MockRepository_FindByHashPrefix_Call) RunAndReturn(run func(ctx context.Context, prefix string) (*media.Media, error)) *MockRepository_FindByHashPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByID(ctx context.Context, id int) (*media.Media, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*media.Media, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *media.Media); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) FindByID(ctx any, id any) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(media1 *media.Media, err error) *MockRepository_FindByID_Call {
	_c.Call.Return(media1, err)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*media.Media, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCursor provides a mock function for the type MockRepository
func (_mock *MockRepository) ListByCursor(ctx context.Context, userID int, limit int, beforeID int) ([]*media.Media, error) {
	ret := _mock.Called(ctx, userID, limit, beforeID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCursor")
	}

	var r0 []*media.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*media.Media, error)); ok {
		return returnFunc(ctx, userID, limit, beforeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, int) []*media.Media); ok {
		r0 = returnFunc(ctx, userID, limit, beforeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*media.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, beforeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCursor'
type MockRepository_ListByCursor_Call struct {
	*mock.Call
}

// ListByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
//   - beforeID int
func (_e *MockRepository_Expecter) ListByCursor(ctx any, userID any, limit any, beforeID any) *MockRepository_ListByCursor_Call {
	return &MockRepository_ListByCursor_Call{Call: _e.mock.On("ListByCursor", ctx, userID, limit, beforeID)}
}

func (_c *MockRepository_ListByCursor_Call) Run(run func(ctx context.Context, userID int, limit int, beforeID int)) *MockRepository_ListByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ListByCursor_Call) Return(medias []*media.Media, err error) *MockRepository_ListByCursor_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockRepository_ListByCursor_Call) RunAndReturn(run func(ctx context.Context, userID int, limit int, beforeID int) ([]*media.Media, error)) *MockRepository_ListByCursor_Call {
	_c.Call.Return(run)
	return _c
}
