// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// DeleteProfilePicture provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) DeleteProfilePicture(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfilePicture")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_DeleteProfilePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProfilePicture'
type MockUserRepo_DeleteProfilePicture_Call struct {
	*mock.Call
}

// DeleteProfilePicture is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) DeleteProfilePicture(ctx any, userID any) *MockUserRepo_DeleteProfilePicture_Call {
	return &MockUserRepo_DeleteProfilePicture_Call{Call: _e.mock.On("DeleteProfilePicture", ctx, userID)}
}

func (_c *MockUserRepo_DeleteProfilePicture_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_DeleteProfilePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_DeleteProfilePicture_Call) Return(err error) *MockUserRepo_DeleteProfilePicture_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_DeleteProfilePicture_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockUserRepo_DeleteProfilePicture_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByID(ctx context.Context, userID int) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepo_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockUserRepo_Expecter) GetUserByID(ctx any, userID any) *MockUserRepo_GetUserByID_Call {
	return &MockUserRepo_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserRepo_GetUserByID_Call) Run(run func(ctx context.Context, userID int)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) Return(s string, err error) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID int) (string, error)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfilePicture provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateProfilePicture(ctx context.Context, userID int, profilePicture string) error {
	ret := _mock.Called(ctx, userID, profilePicture)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfilePicture")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, userID, profilePicture)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_UpdateProfilePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfilePicture'
type MockUserRepo_UpdateProfilePicture_Call struct {
	*mock.Call
}

// UpdateProfilePicture is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - profilePicture string
func (_e *MockUserRepo_Expecter) UpdateProfilePicture(ctx any, userID any, profilePicture any) *MockUserRepo_UpdateProfilePicture_Call {
	return &MockUserRepo_UpdateProfilePicture_Call{Call: _e.mock.On("UpdateProfilePicture", ctx, userID, profilePicture)}
}

func (_c *MockUserRepo_UpdateProfilePicture_Call) Run(run func(ctx context.Context, userID int, profilePicture string)) *MockUserRepo_UpdateProfilePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateProfilePicture_Call) Return(err error) *MockUserRepo_UpdateProfilePicture_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_UpdateProfilePicture_Call) RunAndReturn(run func(ctx context.Context, userID int, profilePicture string) error) *MockUserRepo_UpdateProfilePicture_Call {
	_c.Call.Return(run)
	return _c
}
