// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockStorage
func (_mock *MockStorage) Delete(filePath string) error {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(filePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - filePath string
func (_e *MockStorage_Expecter) Delete(filePath any) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", filePath)}
}

func (_c *MockStorage_Delete_Call) Run(run func(filePath string)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(err error) *MockStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(filePath string) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type MockStorage
func (_mock *MockStorage) GetURL(filePath string) string {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(filePath)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStorage_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockStorage_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - filePath string
func (_e *MockStorage_Expecter) GetURL(filePath any) *MockStorage_GetURL_Call {
	return &MockStorage_GetURL_Call{Call: _e.mock.On("GetURL", filePath)}
}

func (_c *MockStorage_GetURL_Call) Run(run func(filePath string)) *MockStorage_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_GetURL_Call) Return(s string) *MockStorage_GetURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStorage_GetURL_Call) RunAndReturn(run func(filePath string) string) *MockStorage_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockStorage
func (_mock *MockStorage) Save(filename string, reader io.Reader) (string, error) {
	ret := _mock.Called(filename, reader)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, io.Reader) (string, error)); ok {
		return returnFunc(filename, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(string, io.Reader) string); ok {
		r0 = returnFunc(filename, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, io.Reader) error); ok {
		r1 = returnFunc(filename, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - filename string
//   - reader io.Reader
func (_e *MockStorage_Expecter) Save(filename any, reader any) *MockStorage_Save_Call {
	return &MockStorage_Save_Call{Call: _e.mock.On("Save", filename, reader)}
}

func (_c *MockStorage_Save_Call) Run(run func(filename string, reader io.Reader)) *MockStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Save_Call) Return(s string, err error) *MockStorage_Save_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_Save_Call) RunAndReturn(run func(filename string, reader io.Reader) (string, error)) *MockStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}
