// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAliasDeleter creates a new instance of MockAliasDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAliasDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAliasDeleter {
	mock := &MockAliasDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAliasDeleter is an autogenerated mock type for the AliasDeleter type
type MockAliasDeleter struct {
	mock.Mock
}

type MockAliasDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAliasDeleter) EXPECT() *MockAliasDeleter_Expecter {
	return &MockAliasDeleter_Expecter{mock: &_m.Mock}
}

// DeleteByContentID provides a mock function for the type MockAliasDeleter
func (_mock *MockAliasDeleter) DeleteByContentID(ctx context.Context, contentID int) error {
	ret := _mock.Called(ctx, contentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByContentID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, contentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAliasDeleter_DeleteByContentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByContentID'
type MockAliasDeleter_DeleteByContentID_Call struct {
	*mock.Call
}

// DeleteByContentID is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID int
func (_e *MockAliasDeleter_Expecter) DeleteByContentID(ctx any, contentID any) *MockAliasDeleter_DeleteByContentID_Call {
	return &MockAliasDeleter_DeleteByContentID_Call{Call: _e.mock.On("DeleteByContentID", ctx, contentID)}
}

func (_c *MockAliasDeleter_DeleteByContentID_Call) Run(run func(ctx context.Context, contentID int)) *MockAliasDeleter_DeleteByContentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAliasDeleter_DeleteByContentID_Call) Return(err error) *MockAliasDeleter_DeleteByContentID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAliasDeleter_DeleteByContentID_Call) RunAndReturn(run func(ctx context.Context, contentID int) error) *MockAliasDeleter_DeleteByContentID_Call {
	_c.Call.Return(run)
	return _c
}
