// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/content"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommentRepository creates a new instance of MockCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentRepository {
	mock := &MockCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommentRepository is an autogenerated mock type for the CommentRepository type
type MockCommentRepository struct {
	mock.Mock
}

type MockCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentRepository) EXPECT() *MockCommentRepository_Expecter {
	return &MockCommentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) Create(ctx context.Context, comment *content.Comment) error {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *content.Comment) error); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *content.Comment
func (_e *MockCommentRepository_Expecter) Create(ctx any, comment any) *MockCommentRepository_Create_Call {
	return &MockCommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, comment)}
}

func (_c *MockCommentRepository_Create_Call) Run(run func(ctx context.Context, comment *content.Comment)) *MockCommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *content.Comment
		if args[1] != nil {
			arg1 = args[1].(*content.Comment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_Create_Call) Return(err error) *MockCommentRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, comment *content.Comment) error) *MockCommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCommentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCommentRepository_Expecter) Delete(ctx any, id any) *MockCommentRepository_Delete_Call {
	return &MockCommentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCommentRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockCommentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_Delete_Call) Return(err error) *MockCommentRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommentRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockCommentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) DeleteByUserID(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommentRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockCommentRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockCommentRepository_Expecter) DeleteByUserID(ctx any, userID any) *MockCommentRepository_DeleteByUserID_Call {
	return &MockCommentRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockCommentRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockCommentRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_DeleteByUserID_Call) Return(err error) *MockCommentRepository_DeleteByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommentRepository_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockCommentRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByContentID provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) GetByContentID(ctx context.Context, contentID int) ([]*content.Comment, error) {
	ret := _mock.Called(ctx, contentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByContentID")
	}

	var r0 []*content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*content.Comment, error)); ok {
		return returnFunc(ctx, contentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*content.Comment); ok {
		r0 = returnFunc(ctx, contentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, contentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepository_GetByContentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByContentID'
type MockCommentRepository_GetByContentID_Call struct {
	*mock.Call
}

// GetByContentID is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID int
func (_e *MockCommentRepository_Expecter) GetByContentID(ctx any, contentID any) *MockCommentRepository_GetByContentID_Call {
	return &MockCommentRepository_GetByContentID_Call{Call: _e.mock.On("GetByContentID", ctx, contentID)}
}

func (_c *MockCommentRepository_GetByContentID_Call) Run(run func(ctx context.Context, contentID int)) *MockCommentRepository_GetByContentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_GetByContentID_Call) Return(comments []*content.Comment, err error) *MockCommentRepository_GetByContentID_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockCommentRepository_GetByContentID_Call) RunAndReturn(run func(ctx context.Context, contentID int) ([]*content.Comment, error)) *MockCommentRepository_GetByContentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByContentIDForModeration provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) GetByContentIDForModeration(ctx context.Context, contentID int) ([]*content.Comment, error) {
	ret := _mock.Called(ctx, contentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByContentIDForModeration")
	}

	var r0 []*content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*content.Comment, error)); ok {
		return returnFunc(ctx, contentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*content.Comment); ok {
		r0 = returnFunc(ctx, contentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, contentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepository_GetByContentIDForModeration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByContentIDForModeration'
type MockCommentRepository_GetByContentIDForModeration_Call struct {
	*mock.Call
}

// GetByContentIDForModeration is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID int
func (_e *MockCommentRepository_Expecter) GetByContentIDForModeration(ctx any, contentID any) *MockCommentRepository_GetByContentIDForModeration_Call {
	return &MockCommentRepository_GetByContentIDForModeration_Call{Call: _e.mock.On("GetByContentIDForModeration", ctx, contentID)}
}

func (_c *MockCommentRepository_GetByContentIDForModeration_Call) Run(run func(ctx context.Context, contentID int)) *MockCommentRepository_GetByContentIDForModeration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_GetByContentIDForModeration_Call) Return(comments []*content.Comment, err error) *MockCommentRepository_GetByContentIDForModeration_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockCommentRepository_GetByContentIDForModeration_Call) RunAndReturn(run func(ctx context.Context, contentID int) ([]*content.Comment, error)) *MockCommentRepository_GetByContentIDForModeration_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) GetByID(ctx context.Context, id int) (*content.Comment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*content.Comment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *content.Comment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCommentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCommentRepository_Expecter) GetByID(ctx any, id any) *MockCommentRepository_GetByID_Call {
	return &MockCommentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCommentRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockCommentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_GetByID_Call) Return(comment *content.Comment, err error) *MockCommentRepository_GetByID_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockCommentRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*content.Comment, error)) *MockCommentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStatus provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) GetByStatus(ctx context.Context, status content.CommentStatus) ([]*content.Comment, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetByStatus")
	}

	var r0 []*content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, content.CommentStatus) ([]*content.Comment, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, content.CommentStatus) []*content.Comment); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, content.CommentStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepository_GetByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStatus'
type MockCommentRepository_GetByStatus_Call struct {
	*mock.Call
}

// GetByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status content.CommentStatus
func (_e *MockCommentRepository_Expecter) GetByStatus(ctx any, status any) *MockCommentRepository_GetByStatus_Call {
	return &MockCommentRepository_GetByStatus_Call{Call: _e.mock.On("GetByStatus", ctx, status)}
}

func (_c *MockCommentRepository_GetByStatus_Call) Run(run func(ctx context.Context, status content.CommentStatus)) *MockCommentRepository_GetByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 content.CommentStatus
		if args[1] != nil {
			arg1 = args[1].(content.CommentStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_GetByStatus_Call) Return(comments []*content.Comment, err error) *MockCommentRepository_GetByStatus_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockCommentRepository_GetByStatus_Call) RunAndReturn(run func(ctx context.Context, status content.CommentStatus) ([]*content.Comment, error)) *MockCommentRepository_GetByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) GetByUserID(ctx context.Context, userID int) ([]*content.Comment, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*content.Comment, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*content.Comment); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockCommentRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockCommentRepository_Expecter) GetByUserID(ctx any, userID any) *MockCommentRepository_GetByUserID_Call {
	return &MockCommentRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockCommentRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockCommentRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_GetByUserID_Call) Return(comments []*content.Comment, err error) *MockCommentRepository_GetByUserID_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockCommentRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*content.Comment, error)) *MockCommentRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) UpdateStatus(ctx context.Context, id int, status content.CommentStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, content.CommentStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommentRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockCommentRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - status content.CommentStatus
func (_e *MockCommentRepository_Expecter) UpdateStatus(ctx any, id any, status any) *MockCommentRepository_UpdateStatus_Call {
	return &MockCommentRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockCommentRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id int, status content.CommentStatus)) *MockCommentRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 content.CommentStatus
		if args[2] != nil {
			arg2 = args[2].(content.CommentStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommentRepository_UpdateStatus_Call) Return(err error) *MockCommentRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommentRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id int, status content.CommentStatus) error) *MockCommentRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
