// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoleChecker creates a new instance of MockRoleChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleChecker {
	mock := &MockRoleChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoleChecker is an autogenerated mock type for the RoleChecker type
type MockRoleChecker struct {
	mock.Mock
}

type MockRoleChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleChecker) EXPECT() *MockRoleChecker_Expecter {
	return &MockRoleChecker_Expecter{mock: &_m.Mock}
}

// CanManageType provides a mock function for the type MockRoleChecker
func (_mock *MockRoleChecker) CanManageType(role string, postType string) bool {
	ret := _mock.Called(role, postType)

	if len(ret) == 0 {
		panic("no return value specified for CanManageType")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(role, postType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRoleChecker_CanManageType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanManageType'
type MockRoleChecker_CanManageType_Call struct {
	*mock.Call
}

// CanManageType is a helper method to define mock.On call
//   - role string
//   - postType string
func (_e *MockRoleChecker_Expecter) CanManageType(role any, postType any) *MockRoleChecker_CanManageType_Call {
	return &MockRoleChecker_CanManageType_Call{Call: _e.mock.On("CanManageType", role, postType)}
}

func (_c *MockRoleChecker_CanManageType_Call) Run(run func(role string, postType string)) *MockRoleChecker_CanManageType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoleChecker_CanManageType_Call) Return(b bool) *MockRoleChecker_CanManageType_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRoleChecker_CanManageType_Call) RunAndReturn(run func(role string, postType string) bool) *MockRoleChecker_CanManageType_Call {
	_c.Call.Return(run)
	return _c
}

// CanPublish provides a mock function for the type MockRoleChecker
func (_mock *MockRoleChecker) CanPublish(role string) bool {
	ret := _mock.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for CanPublish")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(role)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRoleChecker_CanPublish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanPublish'
type MockRoleChecker_CanPublish_Call struct {
	*mock.Call
}

// CanPublish is a helper method to define mock.On call
//   - role string
func (_e *MockRoleChecker_Expecter) CanPublish(role any) *MockRoleChecker_CanPublish_Call {
	return &MockRoleChecker_CanPublish_Call{Call: _e.mock.On("CanPublish", role)}
}

func (_c *MockRoleChecker_CanPublish_Call) Run(run func(role string)) *MockRoleChecker_CanPublish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoleChecker_CanPublish_Call) Return(b bool) *MockRoleChecker_CanPublish_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRoleChecker_CanPublish_Call) RunAndReturn(run func(role string) bool) *MockRoleChecker_CanPublish_Call {
	_c.Call.Return(run)
	return _c
}

// IsAdmin provides a mock function for the type MockRoleChecker
func (_mock *MockRoleChecker) IsAdmin(role string) bool {
	ret := _mock.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for IsAdmin")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(role)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRoleChecker_IsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAdmin'
type MockRoleChecker_IsAdmin_Call struct {
	*mock.Call
}

// IsAdmin is a helper method to define mock.On call
//   - role string
func (_e *MockRoleChecker_Expecter) IsAdmin(role any) *MockRoleChecker_IsAdmin_Call {
	return &MockRoleChecker_IsAdmin_Call{Call: _e.mock.On("IsAdmin", role)}
}

func (_c *MockRoleChecker_IsAdmin_Call) Run(run func(role string)) *MockRoleChecker_IsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoleChecker_IsAdmin_Call) Return(b bool) *MockRoleChecker_IsAdmin_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRoleChecker_IsAdmin_Call) RunAndReturn(run func(role string) bool) *MockRoleChecker_IsAdmin_Call {
	_c.Call.Return(run)
	return _c
}
