// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aristorinjuang/lesstruct/internal/domain/content"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteComment provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) DeleteComment(ctx context.Context, commentID int) error {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceInterface_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockServiceInterface_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID int
func (_e *MockServiceInterface_Expecter) DeleteComment(ctx any, commentID any) *MockServiceInterface_DeleteComment_Call {
	return &MockServiceInterface_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, commentID)}
}

func (_c *MockServiceInterface_DeleteComment_Call) Run(run func(ctx context.Context, commentID int)) *MockServiceInterface_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_DeleteComment_Call) Return(err error) *MockServiceInterface_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceInterface_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, commentID int) error) *MockServiceInterface_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOwnComment provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) DeleteOwnComment(ctx context.Context, commentID int, userID int) error {
	ret := _mock.Called(ctx, commentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOwnComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, commentID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceInterface_DeleteOwnComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOwnComment'
type MockServiceInterface_DeleteOwnComment_Call struct {
	*mock.Call
}

// DeleteOwnComment is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID int
//   - userID int
func (_e *MockServiceInterface_Expecter) DeleteOwnComment(ctx any, commentID any, userID any) *MockServiceInterface_DeleteOwnComment_Call {
	return &MockServiceInterface_DeleteOwnComment_Call{Call: _e.mock.On("DeleteOwnComment", ctx, commentID, userID)}
}

func (_c *MockServiceInterface_DeleteOwnComment_Call) Run(run func(ctx context.Context, commentID int, userID int)) *MockServiceInterface_DeleteOwnComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_DeleteOwnComment_Call) Return(err error) *MockServiceInterface_DeleteOwnComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceInterface_DeleteOwnComment_Call) RunAndReturn(run func(ctx context.Context, commentID int, userID int) error) *MockServiceInterface_DeleteOwnComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetComment provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) GetComment(ctx context.Context, commentID int) (*content.Comment, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetComment")
	}

	var r0 *content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*content.Comment, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *content.Comment); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_GetComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComment'
type MockServiceInterface_GetComment_Call struct {
	*mock.Call
}

// GetComment is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID int
func (_e *MockServiceInterface_Expecter) GetComment(ctx any, commentID any) *MockServiceInterface_GetComment_Call {
	return &MockServiceInterface_GetComment_Call{Call: _e.mock.On("GetComment", ctx, commentID)}
}

func (_c *MockServiceInterface_GetComment_Call) Run(run func(ctx context.Context, commentID int)) *MockServiceInterface_GetComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_GetComment_Call) Return(comment *content.Comment, err error) *MockServiceInterface_GetComment_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockServiceInterface_GetComment_Call) RunAndReturn(run func(ctx context.Context, commentID int) (*content.Comment, error)) *MockServiceInterface_GetComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentsByUserID provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) GetCommentsByUserID(ctx context.Context, userID int) ([]*content.Comment, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsByUserID")
	}

	var r0 []*content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*content.Comment, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*content.Comment); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_GetCommentsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentsByUserID'
type MockServiceInterface_GetCommentsByUserID_Call struct {
	*mock.Call
}

// GetCommentsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockServiceInterface_Expecter) GetCommentsByUserID(ctx any, userID any) *MockServiceInterface_GetCommentsByUserID_Call {
	return &MockServiceInterface_GetCommentsByUserID_Call{Call: _e.mock.On("GetCommentsByUserID", ctx, userID)}
}

func (_c *MockServiceInterface_GetCommentsByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockServiceInterface_GetCommentsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_GetCommentsByUserID_Call) Return(comments []*content.Comment, err error) *MockServiceInterface_GetCommentsByUserID_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockServiceInterface_GetCommentsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*content.Comment, error)) *MockServiceInterface_GetCommentsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentsForContent provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) GetCommentsForContent(ctx context.Context, contentID int) ([]*content.Comment, error) {
	ret := _mock.Called(ctx, contentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsForContent")
	}

	var r0 []*content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*content.Comment, error)); ok {
		return returnFunc(ctx, contentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*content.Comment); ok {
		r0 = returnFunc(ctx, contentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, contentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_GetCommentsForContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentsForContent'
type MockServiceInterface_GetCommentsForContent_Call struct {
	*mock.Call
}

// GetCommentsForContent is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID int
func (_e *MockServiceInterface_Expecter) GetCommentsForContent(ctx any, contentID any) *MockServiceInterface_GetCommentsForContent_Call {
	return &MockServiceInterface_GetCommentsForContent_Call{Call: _e.mock.On("GetCommentsForContent", ctx, contentID)}
}

func (_c *MockServiceInterface_GetCommentsForContent_Call) Run(run func(ctx context.Context, contentID int)) *MockServiceInterface_GetCommentsForContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_GetCommentsForContent_Call) Return(comments []*content.Comment, err error) *MockServiceInterface_GetCommentsForContent_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockServiceInterface_GetCommentsForContent_Call) RunAndReturn(run func(ctx context.Context, contentID int) ([]*content.Comment, error)) *MockServiceInterface_GetCommentsForContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentsForModeration provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) GetCommentsForModeration(ctx context.Context, contentID int) ([]*content.Comment, error) {
	ret := _mock.Called(ctx, contentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsForModeration")
	}

	var r0 []*content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*content.Comment, error)); ok {
		return returnFunc(ctx, contentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*content.Comment); ok {
		r0 = returnFunc(ctx, contentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, contentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_GetCommentsForModeration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentsForModeration'
type MockServiceInterface_GetCommentsForModeration_Call struct {
	*mock.Call
}

// GetCommentsForModeration is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID int
func (_e *MockServiceInterface_Expecter) GetCommentsForModeration(ctx any, contentID any) *MockServiceInterface_GetCommentsForModeration_Call {
	return &MockServiceInterface_GetCommentsForModeration_Call{Call: _e.mock.On("GetCommentsForModeration", ctx, contentID)}
}

func (_c *MockServiceInterface_GetCommentsForModeration_Call) Run(run func(ctx context.Context, contentID int)) *MockServiceInterface_GetCommentsForModeration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceInterface_GetCommentsForModeration_Call) Return(comments []*content.Comment, err error) *MockServiceInterface_GetCommentsForModeration_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockServiceInterface_GetCommentsForModeration_Call) RunAndReturn(run func(ctx context.Context, contentID int) ([]*content.Comment, error)) *MockServiceInterface_GetCommentsForModeration_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedBySlug provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) GetPublishedBySlug(ctx context.Context, slug string, language string) (*content.Content, error) {
	ret := _mock.Called(ctx, slug, language)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedBySlug")
	}

	var r0 *content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*content.Content, error)); ok {
		return returnFunc(ctx, slug, language)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *content.Content); ok {
		r0 = returnFunc(ctx, slug, language)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, slug, language)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_GetPublishedBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedBySlug'
type MockServiceInterface_GetPublishedBySlug_Call struct {
	*mock.Call
}

// GetPublishedBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - language string
func (_e *MockServiceInterface_Expecter) GetPublishedBySlug(ctx any, slug any, language any) *MockServiceInterface_GetPublishedBySlug_Call {
	return &MockServiceInterface_GetPublishedBySlug_Call{Call: _e.mock.On("GetPublishedBySlug", ctx, slug, language)}
}

func (_c *MockServiceInterface_GetPublishedBySlug_Call) Run(run func(ctx context.Context, slug string, language string)) *MockServiceInterface_GetPublishedBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_GetPublishedBySlug_Call) Return(content1 *content.Content, err error) *MockServiceInterface_GetPublishedBySlug_Call {
	_c.Call.Return(content1, err)
	return _c
}

func (_c *MockServiceInterface_GetPublishedBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string, language string) (*content.Content, error)) *MockServiceInterface_GetPublishedBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetTranslations provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) GetTranslations(ctx context.Context, translationGroupID int, excludeID int) ([]*content.Content, error) {
	ret := _mock.Called(ctx, translationGroupID, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for GetTranslations")
	}

	var r0 []*content.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*content.Content, error)); ok {
		return returnFunc(ctx, translationGroupID, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*content.Content); ok {
		r0 = returnFunc(ctx, translationGroupID, excludeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*content.Content)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, translationGroupID, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_GetTranslations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTranslations'
type MockServiceInterface_GetTranslations_Call struct {
	*mock.Call
}

// GetTranslations is a helper method to define mock.On call
//   - ctx context.Context
//   - translationGroupID int
//   - excludeID int
func (_e *MockServiceInterface_Expecter) GetTranslations(ctx any, translationGroupID any, excludeID any) *MockServiceInterface_GetTranslations_Call {
	return &MockServiceInterface_GetTranslations_Call{Call: _e.mock.On("GetTranslations", ctx, translationGroupID, excludeID)}
}

func (_c *MockServiceInterface_GetTranslations_Call) Run(run func(ctx context.Context, translationGroupID int, excludeID int)) *MockServiceInterface_GetTranslations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_GetTranslations_Call) Return(contents []*content.Content, err error) *MockServiceInterface_GetTranslations_Call {
	_c.Call.Return(contents, err)
	return _c
}

func (_c *MockServiceInterface_GetTranslations_Call) RunAndReturn(run func(ctx context.Context, translationGroupID int, excludeID int) ([]*content.Content, error)) *MockServiceInterface_GetTranslations_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitComment provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) SubmitComment(ctx context.Context, contentID int, userID int, req content.CreateCommentRequest) (*content.Comment, error) {
	ret := _mock.Called(ctx, contentID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for SubmitComment")
	}

	var r0 *content.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, content.CreateCommentRequest) (*content.Comment, error)); ok {
		return returnFunc(ctx, contentID, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, content.CreateCommentRequest) *content.Comment); ok {
		r0 = returnFunc(ctx, contentID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*content.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, content.CreateCommentRequest) error); ok {
		r1 = returnFunc(ctx, contentID, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceInterface_SubmitComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitComment'
type MockServiceInterface_SubmitComment_Call struct {
	*mock.Call
}

// SubmitComment is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID int
//   - userID int
//   - req content.CreateCommentRequest
func (_e *MockServiceInterface_Expecter) SubmitComment(ctx any, contentID any, userID any, req any) *MockServiceInterface_SubmitComment_Call {
	return &MockServiceInterface_SubmitComment_Call{Call: _e.mock.On("SubmitComment", ctx, contentID, userID, req)}
}

func (_c *MockServiceInterface_SubmitComment_Call) Run(run func(ctx context.Context, contentID int, userID int, req content.CreateCommentRequest)) *MockServiceInterface_SubmitComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 content.CreateCommentRequest
		if args[3] != nil {
			arg3 = args[3].(content.CreateCommentRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServiceInterface_SubmitComment_Call) Return(comment *content.Comment, err error) *MockServiceInterface_SubmitComment_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockServiceInterface_SubmitComment_Call) RunAndReturn(run func(ctx context.Context, contentID int, userID int, req content.CreateCommentRequest) (*content.Comment, error)) *MockServiceInterface_SubmitComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentStatus provides a mock function for the type MockServiceInterface
func (_mock *MockServiceInterface) UpdateCommentStatus(ctx context.Context, commentID int, status content.CommentStatus) error {
	ret := _mock.Called(ctx, commentID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, content.CommentStatus) error); ok {
		r0 = returnFunc(ctx, commentID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceInterface_UpdateCommentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentStatus'
type MockServiceInterface_UpdateCommentStatus_Call struct {
	*mock.Call
}

// UpdateCommentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID int
//   - status content.CommentStatus
func (_e *MockServiceInterface_Expecter) UpdateCommentStatus(ctx any, commentID any, status any) *MockServiceInterface_UpdateCommentStatus_Call {
	return &MockServiceInterface_UpdateCommentStatus_Call{Call: _e.mock.On("UpdateCommentStatus", ctx, commentID, status)}
}

func (_c *MockServiceInterface_UpdateCommentStatus_Call) Run(run func(ctx context.Context, commentID int, status content.CommentStatus)) *MockServiceInterface_UpdateCommentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 content.CommentStatus
		if args[2] != nil {
			arg2 = args[2].(content.CommentStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceInterface_UpdateCommentStatus_Call) Return(err error) *MockServiceInterface_UpdateCommentStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceInterface_UpdateCommentStatus_Call) RunAndReturn(run func(ctx context.Context, commentID int, status content.CommentStatus) error) *MockServiceInterface_UpdateCommentStatus_Call {
	_c.Call.Return(run)
	return _c
}
